### ISSUE TITLE
server doesn't start on Arch Linux

### ISSUE THREAD

**Issue by washburn94** [synergy/synergy#4764] opened 2015-06-04 11:22 UTC
When I start Synergy, I got this: 
*** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
*** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
("-f", "--no-tray", "--debug", "INFO", "--name", "r2d2", "-c", "/tmp/Synergy.TJ5482", "--address", ":24800")

Any solution or unofficial workaround for the moment?

**Comment by pithium** [comment] 2015-06-04 18:56
I get the same warnings on Slackware and Mint. As long as you specify an IP or hostname avahi is not a factor in how Synergy operates?

I only get these warnings in syslog. With 1.7.3 avahi warnings stopped printing to stdout.

Slackware64 14.1 -avahi 0.6.31
Mint 17 LTS - avahi 0.6.31-4ubuntu1

**Comment by stratus-ss** [comment] 2015-06-08 18:35
I can't reproduce. I have synergy 1.7.3 running fine on 3 arch boxes (and a smattering of Ubuntu for good measure)

**Comment by doubledodge** [comment] 2015-06-09 14:01
I also have the same warning problem as washburn94.  I built synergy from the source on my RPi and I am specifying the Synergy server IP manually but the same messages occur on the client ("OfficeRPi") while my Synergy server lists the following warnings:

NOTE: accepted client connection
WARNING: unrecognised client name "OfficeRPi", check server config
NOTE: disconnecting client "OfficeRPi"
NOTE: client "OfficeRPi" has disconnected
NOTE: accepted client connection
WARNING: unrecognised client name "OfficeRPi", check server config
NOTE: disconnecting client "OfficeRPi"
NOTE: client "OfficeRPi" has disconnected
etc etc etc

**Comment by speaker** [comment] 2015-06-16 22:39
@doubledodge The Warning is the server saying that it doesn't recognize the name of the client so it's not allowing it to connect. If the server and client have the same name entered than there is something else going on.

@washburn94 Those warnings won't case the server to not run, is there any logging coming out that might help? Change the INFO to DEBUG, or even DEBUG2 if DEBUG doesn't seem to help.

**Comment by doubledodge** [comment] 2015-06-19 13:12
Thanks for the comments @speaker but the set-up on the RPi now seems to be working.  Possibly I simply forgot to click APPLY on the server after adding the RPi in the server configuration?  I may never know, however I found a useful way to suppress the avahi errors by editing /etc/avahi/avahi-daemon.conf as described in https://github.com/stephen/airsonos/issues/22#issuecomment-72698318

**Comment by XinyuHou** [comment] 2015-07-20 20:53
@washburn94
It looks like just warning, I can't figure out the issue and have to close it.

**Closed by XinyuHou** 2015-07-20 20:53 UTC

**Comment by dsb005** [comment] 2015-08-07 12:23
Same Problem Here...

*** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
*** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
/usr/lib/synergy/synergy: symbol lookup error: /usr/lib/synergy/synergy: undefined symbol: _ZN6QDebug9putStringEPK5QCharm

**Comment by StayerX** [comment] 2015-09-21 23:22
"sni-qt/8134" WARN  REMOVED void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
*** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
*** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
("-f", "--no-tray", "--debug", "NOTE", "--name", "REMOVED", "--enable-crypto", "-c", "/tmp/qt_temp.TJ8134", "--address", ":24800")

**Comment by themancalledjakob** [comment] 2016-06-09 10:38
and same here on Ubuntu 16.04 Client trying to connect to an OSX 10.11.5 Server:

*** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
*** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
