### ISSUE TITLE
Clipboard from windows client to linux server does not work

### ISSUE THREAD

**Issue by VeNoMouS** [synergy/synergy#4632] opened 2015-05-07 22:45 UTC
Clipboard from linux server to windows works..

```
INFO: screen "wl41028" updated clipboard 0
```

How ever , do not see the same on the client side when selecting and copying windows to linux...

**Comment by speaker** [comment] 2015-06-03 16:06
Closing this as duplicate of #4735 because that issue has additional information.

**Closed** 2015-06-03 16:05 UTC
