### ISSUE TITLE
High CPU usage for Windows service

### ISSUE THREAD

**Issue by msprotz** [synergy/synergy#4721] opened 2015-05-27 15:45 UTC
My synergyd process on Windows 8.1 uses more than 30% CPU all the time, consistently, after I upgraded. Anything I can do to help debug this?

**Comment by nbolton** [comment] 2015-05-27 15:50
Do you get this in 1.7.2? Is it intermittent?

**Comment by msprotz** [comment] 2015-05-27 15:51
I didn't get this in 1.7.2. Yes, it's intermittent, the fan was whizzing for a few minutes. Isn't it weird that I should have the synergyd process running on the client?

**Comment by nbolton** [comment] 2015-05-27 15:52
Did 1.7.2 just crash in this situation, or was it more stable for you?

**Comment by msprotz** [comment] 2015-05-27 15:55
No issues with 1.7.2

**Comment by msprotz** [comment] 2015-05-27 16:02
Here's what happens:

* I start the GUI app
* everything's fine
* I close the GUI app
* synergyd process pops up and uses CPU
* I start the GUI app
* synergd process no longer uses CPU and seems to remain quiet

**Comment by isometriks** [comment] 2015-05-27 20:13
Having the same issue with 1.7.3 on both my client (win8) and server (win7). Trying doing a few things like disabling SSL etc, but seems to be similar to @msprotz where the issue sort of disappears when the GUI is open. 1.7.2 doesn't have the issue.

**Comment by nedludd** [comment] 2015-05-27 21:15
I'm getting the same thing as @msprotz: a consistent 25% CPU for the 1.7.3 synergyd on the client (Win8) when the GUI is closed, and quiet when it is open. 

The server is Linux.  SSL is disabled all around.

**Comment by gerfunked** [comment] 2015-05-27 23:17
I am seeing the same thing on both my Win7 Server and Win7 client PC's. High CPU usage until I open the client window, then it drops. 

This started happening right after I upgraded to 1.7.3.

**Comment by fmalekpour** [comment] 2015-05-28 07:47
Same here, Windows 8.1, works normal when GUI is running, when I close the GUI, CPU usage is still normal, but when I switch to other monitor (MAC in my case), CPU usage of synergyd goes high (about 20%).

**Comment by mrsno** [comment] 2015-05-28 11:14
Same issue here, 20-30% cpu when moving from client / server randomly. 1.7.3 with ssl on.

**Comment by seyrenhe** [comment] 2015-05-29 13:00
Same issue. high cpu usage on windows 8.1 startup

**Comment by DavyNixon** [comment] 2015-05-29 13:49
Same issue here. CPU usage is between 20-25% and goes to 0 when GUI is opened and remains at 0 after it is closed (we'll see for how long).

**Comment by JesseWaas** [comment] 2015-05-29 21:28
Same issue here. Synergyd.exe process shows high CPU usage on both client and server with 1.7.3. 

When GUI is closed, server CPU utilization is around 15% and client around 30%. 

When the GUI is open, CPU utilization is negligible.

Client/server OS = Windows 8.1.

**Comment by XinyuHou** [comment] 2015-05-30 01:16
Could anyone test this nightly?

http://synergy-project.org/nightly?filter=bd3a8

**Comment by JesseWaas** [comment] 2015-05-30 01:42
XinyuHou: I can confirm that this is resolved (for me) when using build (bd3a8). Thanks for the fix!

**Comment by ccoenen** [comment] 2015-05-31 15:49
I can confirm as well. 1.7.3 showed one core maxed out, now with the nightly build it's back at /usually/ zero.

**Comment by memothegreat** [comment] 2015-06-01 10:21
i tried nightly build.. windows 8.1... after a while.. cpu goes back to %30 on synergyd when gui is closed. so it doesnt work i guess.. i did a fresh install...

**Comment by XinyuHou** [comment] 2015-06-01 16:48
@memothegreat 
After how long this issue is back, couple of hours or overnight?

Could you try to do another fresh install from the nightly? This time after uninstall, please check to make sure Synergy service is gone. You can check it by:

1. Win + r
2. Type in services.msc, enter
3. See if you can find a service called Synergy

**Comment by XinyuHou** [comment] 2015-06-01 17:10
@memothegreat 
What log level are you using? Thank you.

**Comment by KrunchMuffin** [comment] 2015-06-01 18:14
so far so good for me.

**Comment by memothegreat** [comment] 2015-06-02 08:32
Sure.. i will try it when i get back to home tonight and post the results.

**Comment by memothegreat** [comment] 2015-06-02 14:17
i tested it on windows 8.1 server and windows 8.1 client. used a 3rd party uninstall tool to be sure no files left.. restarted pc. checked for service.. no Synergy.. 
İnstalled it.. plugin downloaded succesfully.. 

i m using an existing configuration file.. log level is info..
i tested it with ssl and without ssl... tried with auto-config i mean bonjour.. no luck. after 1-2 mins on server synergyd goes up to %25 and client goes up to %30.. i tried chaging log level couple of times. results are the same for me..

**Comment by XinyuHou** [comment] 2015-06-02 16:38
@memothegreat 
Thank you for the information.

I will create a Window8 VM and test it.

**Comment by XinyuHou** [comment] 2015-06-02 22:03
@memothegreat 
I'm sorry to say I can't reproduce it on my side.

Did you install the nightly I posted?

**Comment by KrunchMuffin** [comment] 2015-06-02 22:17
both of mine are on win8 and its running fine since the previous nightly.

**Comment by memothegreat** [comment] 2015-06-03 07:34
Yes. i used synergy-master-bd3a8e9-Windows-x64

**Comment by sthor69** [comment] 2015-06-03 12:16
I experience the same behaviour with a WindowsXP 32bits.
I installed the last 1.7.3 version and today my laptop shutdown twice for what I think is overtermperature. I then looked at Task Manager and I see that synergyd.exe service is permanently using 25% of CPU.

**Comment by XinyuHou** [comment] 2015-06-03 16:36
@sthor69 
Please try this nightly.

http://synergy-project.org/nightly?filter=bd3a8

**Comment by XinyuHou** [comment] 2015-06-03 17:17
@memothegreat 
Does opening GUI solve the problem? Just want to narrow the cause. Thanks.

**Comment by phjr** [comment] 2015-06-03 17:34
In my case yes. Just having the GUI running (even if hidden in systray) seems to work.

**Comment by XinyuHou** [comment] 2015-06-03 18:12
@phjr
Have you tried the nightly I posted?

**Comment by Cpuroast** [comment] 2015-06-03 18:34
Client OSX 10.10
Server Windows 8.1
Synergy version 1.7.3

I was having the "synergyd" high CPU usage issue when the synergy app wasn't open.
Installed "synergy-master-bd3a8e9-Windows-x64.msi" only on the server and the issue seems to have been resolved.

**Comment by phjr** [comment] 2015-06-03 18:53
I installed synergy-master-bd3a8e9-Windows-x64.msi on my client now and it seems to have solved the issue.

**Comment by willianma** [comment] 2015-06-03 22:34
the nighty bd3a8 seems to have fixed the issue. I had to install in the server and client as both of them were in high cpu usage. (version (1.7.3 - May 26, 2015) server side was 10-13% and client sides were 25%)

now is back to normal with nighty build bd3a8..

**Comment by sthor69** [comment] 2015-06-04 06:14
With the last nightly I used to solve the issue of CPU load, I now experience something new: sometimes, nearly once per half an hour, even if nothing seems happening from the INFO log in the GUI, the app stops working. I mean, the connection is still alive, but the pointer cannot move across screens, it is bounded to the server. The only way to re-establish the functionality is to stop both client and server and restart the server and then the client (the opposite does not work).

Does anyone experience this behaviour?

**Comment by XinyuHou** [comment] 2015-06-05 16:43
@memothegreat 
Could you please try this new nightly?
http://synergy-project.org/nightly?filter=7795d68

**Comment by XinyuHou** [comment] 2015-06-05 16:44
@sthor69 
Please search in our issue tracker and see if you can find any similar ticket. If not please raise your issue as a bug.

**Comment by Cpuroast** [comment] 2015-06-05 16:56
Even with the previous bd3a8e9 nightly, the high cpu usage issue was resolved.

Client: OSX 10.10
Server: Windows 8.1

**Comment by AtomicLaser** [comment] 2015-06-07 18:51
Hello, I was having issues with 100% CPU usage on a fresh install of Windows 7 - Couldn't figure out what it was until I saw that the Synergy service was using high CPU processes.  Updated to the nightly 7795d68 and the issue seems to have been resolved for me :)

**Comment by memothegreat** [comment] 2015-06-07 19:19
@XinyuHou Yes. issue seems to be fixed in this version.. thx

**Comment by gerfunked** [comment] 2015-06-08 13:53
High CPU usage occurred right after starting Synergy with release build. Installed the nightly build and it has been running overnight without issue.

Thanks.

**Comment by gerfunked** [comment] 2015-06-09 15:32
I realize this is probably a new bug and may deserve its own thread, but since installing the nightly build I am having trouble with the service staying running. If I walk away and come back in a few hours Synergy service isn't running on my server or client.

**Comment by techjwalker** [comment] 2015-06-16 14:46
Not yet resolved for me, just delayed.

Seems as though sleeping or hibernating, then restoring a laptop or other device (in my case after moving networks) and CPU usage for the Synergy executable jumps back up to a constant 25%.

As well, I seem to now be getting various random disruptions in mouse and keyboard interaction on the client that last between a second to a few seconds.

**Comment by nbolton** [comment] 2015-06-18 17:51
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf

**Comment by ccoenen** [comment] 2015-06-18 19:11
so far, this one seems to work nicely.

**Comment by techjwalker** [comment] 2015-06-18 20:47
I was hesitant, as one of the latest nightly builds from yesterday was causing random complete lockups on the server that could only be resolved with a restart, but it seems like ebb7edf is working fine so far. Will update later with any issues.

**Comment by egustafson** [comment] 2015-06-19 02:46
1.7.4-stable-ebb7edf is running with no problems for me after monitoring cpu use for 4+ hrs.   I'll report further only if I observe problems.  [win7:win7] configuration.

**Comment by nbolton** [comment] 2015-06-19 19:44
Thanks @ccoenen, @techjwalker and @egustafson for letting us know that v1.7.4-stable-ebb7edf fixes this issue.

**Comment by willianma** [comment] 2015-06-19 20:34
regarding the v1.7.4-stable-ebb7edf
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf
installed it just now, seems normal, it takes some days to test, as soon as I am sure is stable (or not) I'll get back to report.

another thing.. regarding the nighty bd3a8
http://synergy-project.org/nightly?filter=bd3a8
I've reported it as working fine but I've noticed high cpu usage in one of my laptops when I was out of my network boundaries. I was in my academic institution network and not authenthicated (no internet) and the cpu was high (25%).. (this happened at the client application)

**Comment by wlodek76** [comment] 2015-06-20 08:22
:+1: 
<b>SOLVED in v1.7.4</b> - nightly build bd3a8e9
No CPU overhead now.

**Comment by benjymous** [comment] 2015-06-23 08:40
Can confirm I was getting the high CPU usage on a Win8.1 slave running 1.7.3.  Just updated it to the 1.7.4 RC and it appears to have gone back down to normal.

**Comment by willianma** [comment] 2015-06-29 02:05
1.7.4-stable-ebb7edf is working fine
by the way, what were the modifications you did from the nighty bd3a8 to the 1.7.4-stable-ebb7edf?
because the bd3a8 was also using high processor when at an unknown network..

but, this version (1.7.4-stable-ebb7edf) and some previous versions seems laggy, quite unusable under wifi networks..
normally i have 1 to 10 ms ping but when happens one only single ping of 150ms, the packets get buffered in your transmit buffer and once the network gets back to normal 1ms it seems to transmit all  the lost packets at once.. then we have a long delay (normally 1 second) and other delays follows like a bottleneck.. (even after the network have got back to normal.. we experience small delays for about 4 to 5 seconds).
have you noticed this also under wifi networks? what do you think it would be a good way to fix it? have you thought about using udp instead of tcp? so those packets wouldn't jamm your tx buffer (i guess)

are you using QoS already?

**Comment by fearless545** [comment] 2015-06-29 14:44
I have had this same issue on Windows 7 client...I had v1.7.3 installed on both machines and after reading this thread (and the bug #4721 ), I re-download and re-installed it on both server and client...unfortunately, the problem still exists for me.
The workaround of running the client software minimized seems to work, so I will leave it running until there is another build that hopefully fixes the issue.

My setup:
   Server: Windows 7 - 64 bit (synergy-v1.7.3-stable-efd0108-Windows-x64.msi)
   Client: Windows 7 32 bit (synergy-v1.7.3-stable-efd0108-Windows-x86.msi)
Downloaded and installed 6/29/2015

**Comment by techjwalker** [comment] 2015-06-29 18:59
I seem to get occasional lockups with ebb7edf now, where I'm entirely unable to use the server computer's mouse or keyboard although no clients are connected. I have to start a shutdown (via power button) to regain control of the desktop again.

**Comment by nyetwurk** [comment] 2015-06-29 19:12
Ditto, and hitting bug 3148.

**Comment by willianma** [comment] 2015-06-30 04:58
by the way Nick, what's happening?
I used to get smooth mouse movement under wifi.. If I install the older versions I get it smooth again.. 
now at this new version even the clipboard is affecting the performance under wifi, as every time it syncs, I have delays.. that's probably because there is no QoS.. (ps. I have no Idea how to deploy Qos but I think it might be possible)
UDP would also improve in my opinion..
anyway.. about a year ago the Synergy application was quite useful, now I'm facing delays under wifi that makes it somehow unusable, as it gives a bad user experience..
my suggestion would be to add more options to enable/disable the newer features and keep the old version features available.. (in my case I just need the old features to connect to one wifi computer, the others I'd prefer using the newer features because the mouse movement is smoother)

**Comment by ace518** [comment] 2015-07-06 22:09
Same issue as above.  High cpu.  Open GUI goes away.  I'm on 1.7.3  
Windows 10 build 10158

**Comment by jml674** [comment] 2015-07-07 12:35
Synergyd.exe takes 50% of my CPU. Windows7 sp1, 1.7.3

**Comment by jonmann20** [comment] 2015-07-09 16:44
Still happening.  High CPU usage.  Windows 8.1 synergyd.  Made the computer completely unresponsive had to hard reboot.  Planning to uninstall

**Comment by mihaibirsan** [comment] 2015-07-13 09:56
I'm still experiencing the issue in Windows 7 SP1, 64-bit.

When I disconnect from the network (eg. taking the laptop to a coffee shop) the synergyd process take a full CPU and drains the battery.

**Comment by meshosk** [comment] 2015-07-13 13:00
Got the same CPU usage issue on client with Windows 8.1, 64. When I close GUI the CPU load jump from 0.8% to 30% on synergyd.exe (also synergy icon from the notification area disappear). So i must have GUI minimalized.  My client is a ultra-book, so im not happy with this unnecessary battery drain. Server is running Debian and both running 1.7.3.

**Comment by adrianopedro** [comment] 2015-07-13 14:36
Same here...
WIthout GUI the CPU usage for synergyd is about 50%...

Any update?

Regards,
AP

**Comment by XinyuHou** [comment] 2015-07-13 21:22
Should be fixed by 2de276cfca71a79df31a1d4a89d412212279a1a5.

Can anyone test this nightly?

http://synergy-project.org/nightly?filter=2de276

**Comment by meshosk** [comment] 2015-07-14 12:15
Looks this nightly fix the CPU issue :+1:  What about icon in windows notification area? Icon stays in the area only if I choose "windows > hide" in GUI window menu. If I close it the icon disappears and service still runs.I easily can forget (which is everytime) that it is still running.

**Comment by XinyuHou** [comment] 2015-07-14 17:12
@adrianopedro @mihaibirsan 
Have you tried the nightly?

http://synergy-project.org/nightly?filter=2de276

**Comment by XinyuHou** [comment] 2015-07-14 17:13
@meshosk 
Please go to #4800

**Comment by shpond** [comment] 2015-07-15 14:31
I'm seeing the same issue. synergyd.exe using 50% of the processor, but as soon as I open the GUI, it drops to normal levels. Windows 7 64-bit running 1.7.3 as a client. Server is also running 1.7.3 but on Xubuntu 14.04.

**Comment by BigBlueHat** [comment] 2015-07-15 18:41
Just tested the nightly @XinyuHou. CPU usage is much better! < 1% so far. Mouse seems a bit jumpy, however.

1.7.3 on Mac OS 10.6.8 server.
1.7.4~2de276 on Windows 8.1 client.
Encryption off on both sides (due to "crypto disabled because of ns plugin not available")

Cheers!

**Comment by XinyuHou** [comment] 2015-07-15 18:54
@BigBlueHat @meshosk 
Sorry guys, the cpu usage fix causes another bug. I have to revert the change and try to fix it in another way.

**Comment by KrunchMuffin** [comment] 2015-07-16 14:54
I had to reinstall and I am getting the hi cpu again with this build synergy-v1.7.4-stable-a1106b0-Windows-x64.msi. Should I be trying a different build?

**Comment by XinyuHou** [comment] 2015-07-16 19:56
@KrunchMuffin 
Fix is still on the process, please sit tight.

**Comment by h3po** [comment] 2015-07-19 18:13
what is the latest version that this bug does not appear on? i just updated to 1.7.4-stable-a1106b0 and still have the problem on both client and server.

**Comment by XinyuHou** [comment] 2015-07-21 22:48
Fixed by 4dd40457cbb8bdde0049e85f5f7b49dbf0a1bc7d

**Closed by XinyuHou** 2015-07-21 22:48 UTC
Labels: bug

**Comment by XinyuHou** [comment] 2015-07-21 22:53
@h3po @KrunchMuffin @shpond @adrianopedro @mihaibirsan @jonmann20 @jml674 @ace518 @techjwalker @fearless545
Please test nightyly 4dd404
http://synergy-project.org/nightly?filter=4dd404

**Comment by garfield2003** [comment] 2015-07-24 07:47
for me it looks good with the nightyly 4dd404 now cpu usage is back to normal level on my Windows 8.1

**Comment by KrunchMuffin** [comment] 2015-07-25 14:30
so far so good

**Comment by xymantec** [comment] 2015-07-28 19:05
Same here just installed on 2 machines and CPU usage is higher then Photoshop lol... something is up, I tried the updated version and it resolved the problem. Thanks :)

**Comment by BigBlueHat** [comment] 2015-07-28 19:22
Working great here!

**Comment by tmhalbert** [comment] 2015-07-29 19:18
nightyly 4dd404 fixed this issue in Windows 10! thank you

**Comment by jamessevener** [comment] 2015-08-01 06:09
Just installed the nightly 4dd404. Running Windows 10 on my laptop with a Linux server. As was stated earlier, seemed to happen when changing networks. I'll report back if I have any more high CPU issues.

**Comment by shpond** [comment] 2015-08-01 13:36
Any idea when this fix will end up in the stable release? Not too keen on
installing nightly builds. Thanks.

**Comment by nbolton** [comment] 2015-08-03 02:15
@shpond We've been trying to release 1.7.4 for weeks, but we've been struggling to pass QA (@the-wes). I'm hoping it'll be ready on Monday, but we shall see.

**Comment by shpond** [comment] 2015-08-03 02:22
Sounds good. Thanks.

**Comment by KrunchMuffin** [comment] 2015-08-05 15:24
is anyone having trouble with CTRL+C (Copy)? I literally have to press it 2-3 times to get the copy to work. Very much a PITA when you're a developer.

**Comment by sthor69** [comment] 2015-08-05 15:29
Yes, I experienced the same issue.
But as using mouse (right-click and then "Copy") everything is fine, I 
didn't pay too much attention to the issue and I don't have a statistic 
(sometimes it works sometimes it does not).

**Comment by KrunchMuffin** [comment] 2015-08-05 15:34
mouse does same thing for me.

**Comment by Yulien37** [comment] 2015-08-10 15:37
Same problem with cpu usage.
Server : MacOS 10.10.4 ; Client : Windows 7 64 ; Synergy 1.7.3
Waiting for 1.7.4, I autostart the GUI as a workaround, and now everything is fine.

**Comment by tiancheng91** [comment] 2015-08-18 17:19
Problem with high cpu usage in client mode .
Server: Windows 10
Client: OSX 10.10.4,  macbook pro 2015
Synergy Client:  synergy-master-alpha-5da7290-MacOSX1010-x86_64.dmg  (latest)

**Comment by dpgt** [comment] 2015-08-28 20:55
Problem with high cpu usage in client mode. Synergy is using about 25-30% of my CPU. It makes no difference if I open the GUI. Stopping and starting from the GUI also does nothing.
Server: Windows 10
Client: Windows 7
Synergy version: 1.7.4
