### ISSUE TITLE
Incorrect plugin downloads on Debian and Mint

### ISSUE THREAD

**Issue by VeNoMouS** [synergy/synergy#4565] opened 2015-04-23 00:10 UTC
@XinyuHou: @the-wes told me that the GUI is actually downloading the CentOS version of the plugin on Debian and Linux Mint...

Server-side plugin MD5 sums:
```
ebae00b35139a22494f7b74cda31f3af  Linux-i686-deb/libns.so
b0f38ec472de0c0df96c2235cdc680da  Linux-i686-rpm/libns.so
33f50f4122ffe40cc28d9810a9ed4639  Linux-x86_64-deb/libns.so
a46812ff53a8c25a4c5ac13338a81b6e  Linux-x86_64-rpm/libns.so
```

When I activate on Debian, it downloads the 'rpm' libns.so:

![image](https://cloud.githubusercontent.com/assets/313427/7746410/e53caf1c-ffa9-11e4-9477-45f6cdff43d2.png)

--

I'm running jessie.... with synergy 1.7.0 with ssl was working...

With a ldd we see that the following libs do not exist on debian..
```
        libssl.so.10 => not found
        libcrypto.so.10 => not found
```

So if we try to symlink to the closet match being libcryto.so.1.0.0 and libssl.so.1.0.0, then if we check more in detail with ldd we see functions missing between the two..

```
symbol SSL_CTX_check_private_key, version libssl.so.10 not defined in file libssl.so.10 with link time reference        (/root/.synergy/plugins/libns.so)
symbol SSL_CTX_free, version libssl.so.10 not defined in file libssl.so.10 with link time reference     (/root/.synergy/plugins/libns.so)
symbol OPENSSL_add_all_algorithms_noconf, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference  (/root/.synergy/plugins/libns.so)
symbol SSL_load_error_strings, version libssl.so.10 not defined in file libssl.so.10 with link time reference   (/root/.synergy/plugins/libns.so)
symbol SSL_accept, version libssl.so.10 not defined in file libssl.so.10 with link time reference       (/root/.synergy/plugins/libns.so)
symbol SSL_write, version libssl.so.10 not defined in file libssl.so.10 with link time reference        (/root/.synergy/plugins/libns.so)
symbol X509_digest, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference        (/root/.synergy/plugins/libns.so)
symbol EVP_sha1, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference   (/root/.synergy/plugins/libns.so)
symbol SSL_free, version libssl.so.10 not defined in file libssl.so.10 with link time reference (/root/.synergy/plugins/libns.so)
symbol SSL_CTX_new, version libssl.so.10 not defined in file libssl.so.10 with link time reference      (/root/.synergy/plugins/libns.so)
symbol X509_NAME_oneline, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference  (/root/.synergy/plugins/libns.so)
symbol SSL_new, version libssl.so.10 not defined in file libssl.so.10 with link time reference  (/root/.synergy/plugins/libns.so)
symbol SSL_set_fd, version libssl.so.10 not defined in file libssl.so.10 with link time reference       (/root/.synergy/plugins/libns.so)
symbol SSL_CTX_use_certificate_file, version libssl.so.10 not defined in file libssl.so.10 with link time reference     (/root/.synergy/plugins/libns.so)
symbol X509_get_subject_name, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference      (/root/.synergy/plugins/libns.so)
symbol SSL_CTX_use_PrivateKey_file, version libssl.so.10 not defined in file libssl.so.10 with link time reference      (/root/.synergy/plugins/libns.so)
symbol SSL_shutdown, version libssl.so.10 not defined in file libssl.so.10 with link time reference     (/root/.synergy/plugins/libns.so)
symbol SSL_read, version libssl.so.10 not defined in file libssl.so.10 with link time reference (/root/.synergy/plugins/libns.so)
symbol SSL_library_init, version libssl.so.10 not defined in file libssl.so.10 with link time reference (/root/.synergy/plugins/libns.so)
symbol CRYPTO_free, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference        (/root/.synergy/plugins/libns.so)
symbol ERR_error_string_n, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference (/root/.synergy/plugins/libns.so)
symbol ERR_get_error, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference      (/root/.synergy/plugins/libns.so)
symbol X509_free, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference  (/root/.synergy/plugins/libns.so)
symbol SSL_connect, version libssl.so.10 not defined in file libssl.so.10 with link time reference      (/root/.synergy/plugins/libns.so)
symbol SSLv23_client_method, version libssl.so.10 not defined in file libssl.so.10 with link time reference     (/root/.synergy/plugins/libns.so)
symbol SSL_get_peer_certificate, version libssl.so.10 not defined in file libssl.so.10 with link time reference (/root/.synergy/plugins/libns.so)
symbol ERR_peek_error, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference     (/root/.synergy/plugins/libns.so)
symbol SSLv23_server_method, version libssl.so.10 not defined in file libssl.so.10 with link time reference     (/root/.synergy/plugins/libns.so)
symbol SSL_get_error, version libssl.so.10 not defined in file libssl.so.10 with link time reference    (/root/.synergy/plugins/libns.so)
```

SSL package that libcrypto.so.1.0.0 and libssl.so.1.0.0 is from

```
1.0.1k-3
```

Only way to get this working is to manually compile from source and replace libns.so plugin.

**Comment by VeNoMouS** [comment] 2015-04-23 00:31
Additionally... if you disable SSL , it keeps bugging out on the bad libns.so even tho you have disabled it, and fails to start.. only way to get synergy running is to delete libns from the plugins in order to run in unencrypted mode.

**Comment by recluse2** [comment] 2015-04-23 02:12
Same thing, Running Linux Mint 17.1 client just starts and shuts back down. Back to 1.6.2 with no SSL

**Comment by VeNoMouS** [comment] 2015-04-23 02:14
@recluse2 just compile from src and replace the libns.so till @nbolton fixes it... even tho ive bought this up with many many times about debian

**Comment by TzuLuX** [comment] 2015-05-06 08:04
Same thing, running Synergy server on Linux Mint 17.1, just starts and terminated unexpectedly with:
ERROR: failed to load plugin: libns.so
FATAL: An error occurred: libssl.so.10: cannot open shared object file: No such file or directory

**Comment by qu1nl4n** [comment] 2015-05-06 11:20
Same exact error with Sybergy server on Mint 16.

**Comment by kengdahl** [comment] 2015-05-06 15:34
Same thing, Debian 7.8

**Comment by mayeulk** [comment] 2015-05-06 16:01
same with ubuntu 15.04

**Comment by jdrockho** [comment] 2015-05-06 16:12
Same issue - Debian jessie.  IS there an ETA on 1.73?

**Comment by nbolton** [comment] 2015-05-06 16:14
v1.7.3-stable
Due by May 20, 2015

**Comment by retracement** [comment] 2015-05-07 17:55
For those not wanting to revert from 1.7.3 with a quick work around till fix is issued, see my comment in #4621

**Comment by kepi** [comment] 2015-05-08 10:54
I can wait till May 20, but @nbolton I think regressions like this should be addressed immediately with bugfix release. 

And in case you are announcing new super release to your users, it will be great to at least mention the trouble with Debian so people like me can wait with upgrade :)

**Comment by nbolton** [comment] 2015-05-09 17:19
We plan to fix this in v1.7.3 (the next release).

**Comment by TimOgilvy** [comment] 2015-05-14 01:34
Hi @nbolton, appreciate you are responding here.  I just upgraded because I received your email about this feature, and have now lost time on a busy day chasing a fix. If v1.7.3 is not coming out this week, I strongly recommend notifying all Linux users that they may have issues, and to hold out for that version.  Does your website track who has downloaded a Linux package? If you really want to save face and not confess to all your users that there's a bug, maybe only email Linux users?

I got your email and trusted you, and upgraded.  Your upgrade somewhat betrayed that trust. Customer trust is a small and intangible detail at times, but your promotion emails do suggest that you value it.  Please save other linux/debian users some grief and notify them of the potential issue?

(I'm running Debian Sid).

**Comment by VeNoMouS** [comment] 2015-05-14 03:14
@TimOgilvy as a "fix" to get the encryption running just clone the github source, compile synergy and simply copy the libns.so from the compiled src into the plugins directory... that is what i did to get back up and going with ssl...

**Comment by TimOgilvy** [comment] 2015-05-14 03:19
@VeNoMouS thanks, I'll try that when I have a moment.

**Comment by VeNoMouS** [comment] 2015-05-14 03:23
```
cd build/release
make
```

**Comment by nbolton** [comment] 2015-05-14 04:34
@TimOgilvy I'm sorry about the betrayal of trust, this was not my intention. I should have tested on Debian after updating the build environment, not dong this was foolish. I thought that after releasing a beta for a month all of the major issues like this one would have grabbed my attention, but not so. In future, when changing the build environment, I will include Debian on my "major OS's to test" list.

For now, please downgrade to 1.6.
http://synergy-project.org/download/?alt

@XinyuHou @speaker

**Comment by TimOgilvy** [comment] 2015-05-14 04:37
@nbolton You're a good guy Nick, and synergy is super nifty. Thanks for the response.

**Comment by nbolton** [comment] 2015-05-14 05:01
@TimOgilvy I updated our process so we test on all major OSs after changing the build environment (wiki: [Buildbot](https://github.com/synergy/synergy/wiki/Buildbot)). Can you think of any improvements to this list?

**Comment by TimOgilvy** [comment] 2015-05-14 05:08
Looks pretty complete to me - I did note that you have added unstable Debian, but held Ubuntu at 14.04 I'm not sure if you have any users who run 15.04, but it might be worth adding to the stack if you do?

**Comment by nbolton** [comment] 2015-05-14 05:10
@TimOgilvy Thanks, I added 15.04.

**Comment by recluse2** [comment] 2015-05-14 06:19
I just wanted to throw in a big Thank You too Nick. Been using Synergy for years. People need to understand that this is under heavy development. Things like this happen especially in the Linux community. You frequently have to find workarounds and search forums and read man pages alot. They shouldn't be surprised at all about things like this.

**Comment by nbolton** [comment] 2015-05-14 07:03
Feelin' the love guys! :smile:

**Comment by nbolton** [comment] 2015-05-20 15:19
@jdrockho, sorry we're a little delayed.

v1.7.3-stable
 Due by May 27, 2015

**Comment by nbolton** [comment] 2015-05-21 10:11
@XinyuHou See my notes at the top. When using Debian and Linux Mint, it downloads the 'rpm' plugin instead of the 'deb' plugin.

**Comment by nbolton** [comment] 2015-05-21 10:13
@XinyuHou  Ugh... ok so I'm sorry to be so harsh, but this is a terrible way to figure out if the system is deb or rpm based... https://github.com/synergy/synergy/blob/8c82996fc4b80ef90c2a2f1d72f5353285084e63/src/gui/src/QUtility.cpp#L150

**Comment by nbolton** [comment] 2015-05-21 10:22
Workaround:
```
cd ~/.synergy/plugins
wget http://synergy-project.org/files/plugins/ns/1.0/Linux-x86_64-deb/libns.so
```

**Comment by kevjonesin** [comment] 2015-05-21 16:20
@nbolton is there a 32 bit workaround (please)? I'm running Linux Mint 17 Xfce on multiple 32 bit machines.

p.s.— A warning note next to the 17.2 .deb file on the download page woulda' been a real time saver all around, <wink><hint><nudge>

p.p.s.— Today's bit of a hiccup aside (finally gave in today to the upgrade nag notice on 16.2, doh, bad timing), Synergy is an excellent product and I'm quite grateful to have use of it.

p.p.p.s.— Is 17.3 coming out soon? If so, I'll just stick with 16.2 a bit longer. Already downgraded the machine I added the wonky 17.2 to.
—Kev—

**Comment by nbolton** [comment] 2015-05-21 17:14
Will be fixed by #4696

**Comment by Tejeev** [comment] 2015-05-21 18:07
I'm with @kevjonesin on this.  LOVE Synergy and paid in to help dev and show my appreciation.   But this is the second time now I've given into a nag that left me unworkable at work.  I don't mind the hiccups since it's a good product and I understand what you're going through very well, but could we PLEASE put a news notice next to downloads that might have current relevant bugs?   That way when something pops up that needs special attention we know before the upgrade.

**Comment by nbolton** [comment] 2015-05-21 18:16
@Tejeev Declaring 1.7.2 stable was my mistake, which I will not repeat. The only solution is to make it stable, which we are doing. 1.7.3 will be released on Tuesday (26th May).

**Comment by Tejeev** [comment] 2015-05-21 18:39
Thanks @nbolton.  Either way, just wanted to say that I appreciate your work have been generally happy with the improvements and additions since you started asking us to pay in.  Good product and (I hope) good distribution model.  I hope it works well for y'all.

**Comment by nbolton** [comment] 2015-05-25 19:33
@VeNoMouS I fixed the logic in the GUI in e8a43dd so it now downloads the right plugin. However, SSL is still unstable so it's no good to test. Mine always fails to connect because it exceeds the max retry limit, doh! http://synergy-project.org/nightly?filter=synergy-master-e8a43dd

**Closed** 2015-05-25 19:33 UTC
Labels: bug, priority-urgent

**Comment by wen96** [comment] 2015-05-27 15:06
It is working, thanks!

**Comment by anomaly256** [comment] 2015-07-22 03:58
I know you're not really looking to support Gentoo, but I thought I'd mention it here that I had to perform the symlinking workaround for 1.7.3.  It downloaded the libns.so version that looks for libssl.so.10 instead of libssl.so.1.0.0

        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f91acf94000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f91acbc4000)

Works fine after this.  I wonder though, is there a better way to test for which libns.so to download apart from explicit per-distro rules?  Maybe like testing the 'SONAME' on /usr/lib/libssl.so?

**Comment by nbolton** [comment] 2015-07-22 21:10
@anomaly256 I'm pretty sure this should be a new issue.
