### ISSUE TITLE
Encryption no connect

### ISSUE THREAD

**Issue by zippo-71** [synergy/synergy#4478] opened 2015-03-25 14:22 UTC
Hi im using synergy on windows 7 (server) and ubuntu 1404 desktop(client).

wenn i use the encryption the client can't connect to the server, where is encrytion ist enabled too. Yes with the same password.

regards Andreas

**Comment by cledoux** [comment] 2015-03-25 19:30
Duplicate of #3730?

**Comment by zippo-71** [comment] 2015-03-25 21:18
It Looks like 

Regards Andreas

**Closed** 2015-03-31 07:42 UTC
