### ISSUE TITLE
Regularly drops connection

### ISSUE THREAD

**Issue by krewmarco** [synergy/synergy#4766] opened 2015-06-04 22:39 UTC
1.7.3 on both machines.  Always fixed by restarting  the client and the server.   Let me know if you want a more detailed report.  The logs were copied right after disconnect.

-- Client 
Ubuntu 12.04
Linux marco-Studio-1569 3.13.0-48-generic #80~precise1-Ubuntu SMP Thu Mar 12 19:30:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
---- Client Debug Log
INFO: leaving screen
INFO: entering screen
DEBUG: lost clipboard 1 ownership at time 78738092
DEBUG: lost clipboard 1 ownership at 78738092
INFO: leaving screen
DEBUG: open clipboard 1
INFO: entering screen
DEBUG: ICCCM fill clipboard 1
DEBUG:   available targets: STRING (31)
DEBUG: close clipboard 1
DEBUG: sending clipboard 1 seqnum=9
DEBUG: sent clipboard size=4
INFO: leaving screen
DEBUG: open clipboard 1
DEBUG: ICCCM fill clipboard 1
DEBUG:   available targets: STRING (31)
INFO: entering screen
DEBUG: close clipboard 1
INFO: leaving screen
DEBUG: open clipboard 1
DEBUG: ICCCM fill clipboard 1
DEBUG:   available targets: TARGETS (448), SAVE_TARGETS (464), MULTIPLE (449), STRING (31)
NOTE: server is dead

-- Client Debug Log / Example 2

DEBUG: open clipboard 1
DEBUG: ICCCM fill clipboard 1
DEBUG:   available targets: STRING (31)
DEBUG: close clipboard 1
INFO: leaving screen
DEBUG: open clipboard 0
DEBUG: ICCCM fill clipboard 0
DEBUG:   available targets: TIMESTAMP (450), TARGETS (448), MULTIPLE (449), SAVE_TARGETS (464), UTF8_STRING (299)
DEBUG:   added format 0 for target UTF8_STRING (299) (2240 bytes)
DEBUG: close clipboard 0
DEBUG: sending clipboard 0 seqnum=33
DEBUG: ssl connection closed
DEBUG: sent clipboard size=2252
DEBUG: open clipboard 1
DEBUG: ICCCM fill clipboard 1
DEBUG:   available targets: TARGETS (448), SAVE_TARGETS (464), MULTIPLE (449), STRING (31)
DEBUG:   added format 0 for target UTF8_STRING (299) (30 bytes)
DEBUG: close clipboard 1
---- Client Log Example 3
INFO: leaving screen
INFO: entering screen
INFO: leaving screen
INFO: entering screen
INFO: leaving screen
INFO: entering screen
INFO: leaving screen
INFO: entering screen
INFO: leaving screen
NOTE: disconnected from server

-- Server
Mac OS X 10.9.5 Mavericks
13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
---- Server Debug Log
DEBUG: dropped bogus motion -840,-430
INFO: switch from "ubuntu" to "MARCOs-Mac-mini.local" at 31,345
INFO: entering screen
DEBUG: showing cursor
DEBUG: ssl connection closed
NOTE: client "marco-Studio-1569" has disconnected

-- Server Log Example 2

INFO: switch from "ubuntu" to "MARCOs-Mac-mini.local" at 18,416
INFO: entering screen
DEBUG: showing cursor
INFO: switch from "MARCOs-Mac-mini.local" to "ubuntu" at 1365,381
INFO: leaving screen
DEBUG: hiding cursor
WARNING: cursor may not be visible
INFO: switch from "ubuntu" to "MARCOs-Mac-mini.local" at 80,276
INFO: entering screen
DEBUG: showing cursor
DEBUG: start receiving clipboard data
NOTE: client "marco-Studio-1569" has disconnected

---- Server Log Example 3
DEBUG: opening clipboard
DEBUG: emptying clipboard
DEBUG: closing clipboard
INFO: switch from "MARCOs-Mac-mini.local" to "ubuntu" at 1365,546
INFO: leaving screen
DEBUG: hiding cursor
DEBUG: opening clipboard
DEBUG: closing clipboard
INFO: screen "MARCOs-Mac-mini.local" updated clipboard 0
DEBUG: sending clipboard 0 to "marco-Studio-1569"
WARNING: cursor may not be visible
DEBUG: sent clipboard size=4
ERROR: ssl error occurred (system call failure)
NOTE: client "marco-Studio-1569" has disconnected

**Comment by krewmarco** [comment] 2015-06-05 02:42
I reverted to 1.4.18 on both machines.   Works perfectly!

**Comment by johnny-bit** [comment] 2015-06-08 08:18
Try 1.7.2 or anything pre 1.7.3. I've noticed that 1.7.3 not only has clipboard problems, but randomy hangs/drops connections, especially when there's something IN clipboard on any client.

**Comment by speaker** [comment] 2015-06-16 17:52
Looks to be a duplicate of #4712. This is initially addressed in 1.7.4, and will have additional work in 1.7.5 to improve overall performance and stability.

**Closed by speaker** 2015-06-16 17:52 UTC
