### ISSUE TITLE
Display scaling breaks edge detection on Windows

### ISSUE THREAD

**Issue by OverCaste** [synergy/synergy#5030] opened 2015-09-19 15:31 UTC
1. Open display settings.
2. Set display scaling to greater than 100%.
3. Install or upgrade Synergy.
4. Open Synergy and click "Apply" or "Start".

----

Tested on a windows 10 4k laptop, the option "Change the size of text, apps, and other items" makes synergy think the edge of the screen is not where it physically is.

E.G: Having scaling set to 200% normal size makes synergy think the screen edge is at half the width and half the height of the windows machine.

**Comment by Wintaru** [comment] 2015-09-25 21:16
I'm seeing this as well on a Windows 10 desktop with a Samsung U28D590D monitor. I can switch between windows normally using custom defined hotkeys, is there any way to disable mouse switching until this is fixed?

**Comment by OverCaste** [comment] 2015-09-25 21:18
I managed to resolve the issue by enabling "Disable display scaling on high DPI settings" as well as running on compatibility for the following 2 files:

synergy.exe
synergyc.exe

Hope this works for you.

**Comment by Wintaru** [comment] 2015-09-25 21:20
I'll give it a shot now, thanks.

**Comment by Wintaru** [comment] 2015-09-25 21:31
Didn't work, I'm going to open a new issue since you closed this.

**Comment by harijan** [comment] 2015-09-27 05:15
I fixed this on a Windows 10 host with a 4k monitor.

Under compatibility settings -> Change settings for all users
Do what @OverCaste says and enable "Disable display scaling on high DPI settings" as well as running on Windows 7 compatibility for the following 2 files:
synergyd.exe
synergys.exe

It's possible changing only synergys.exe is needed but I did both and it works for me.

**Comment by Wintaru** [comment] 2015-09-27 13:42
Change Settings for All Users did the trick for me.

**Comment by mzazon** [comment] 2015-10-07 17:52
Confirmed this workaround works on Win10 host with 4K monitor and mac 10.11 1.7.4 thanks!!

**Comment by XinyuHou** [comment] 2015-10-19 20:54
Fixed by 5910ebef5f4e8bc2eaa5325bc3b9c44da1f3b137

**Closed** 2015-11-12 17:35 UTC
Labels: bug

**Comment by ebalsumgo** [comment] 2015-12-07 18:23
This does not work on my windows 10 server using both 1.7.5 and latest 1.8-dev build

**Comment by XinyuHou** [comment] 2015-12-07 18:32
@ebalsumgo 
Please send us some log on your server side.

Do you mean 1.7.5 on server and latest 1.8-dev on client?

**Comment by ebalsumgo** [comment] 2015-12-07 18:34
No i mean i tried both 1.7.5 and 1.8-dev on the server and in both cases my mouse was leaving the screen too early, about a quarter of my screen size too early.

**Comment by XinyuHou** [comment] 2015-12-07 18:56
@ebalsumgo 
Please send us some log on your server side with 1.7.5 installed.

**Comment by jeffboulanger** [comment] 2015-12-08 23:59
Same problem, here's the log http://pastebin.com/CNHNtWde

**Comment by XinyuHou** [comment] 2015-12-09 17:22
@jeffboulanger 
Unfortunately we don't have a good support for different dpi settings for different monitors connected to the same machine.

Would you mind raise a new issue for that?

**Comment by jeffboulanger** [comment] 2015-12-09 19:07
@XinyuHou Done #5146

**Comment by LizJB** [comment] 2016-04-16 15:32
Had the same issue, this workaround worked for me. 2 x Win10, 3 screens all different sizes and resolutions.  Thanks much.
