### ISSUE TITLE
Running old version of the SSL plugin results in error "called a function you should not call"

### ISSUE THREAD

**Issue by stockmaster** [synergy/synergy#4719] opened 2015-05-27 15:19 UTC
Just installed 1.7.3 on all my win8.1 machines. Rebooted them all, activated all

Errors non stop as follow, followed by client freezing and crash.

NOTE: starting server
NOTE: config file: C:/Users/STOCKM~1/AppData/Local/Temp/qt_temp.q27796
NOTE: log level: INFO
INFO: service command updated
INFO: starting new process
activeDesktop:Default
INFO: starting new process
INFO: drag and drop enabled
NOTE: started server, waiting for clients
INFO: watchdog status: ok
NOTE: accepted client connection
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to connect secure socket
INFO: server connection may not be secure

Not sure what to do. Advise please?

Regards

**Comment by srvrmnky** [comment] 2015-05-27 15:24
I was having this issue - and you have to make sure the new ns plugin downloads successfully. Make sure the server is not running and go through the setup wizard, and make sure it installs correctly at the end.

On the other hand, I just tried to run the update on a freshly upgraded Fedora 22 install, and the wizard was unable to determine 'what type' of Linux I was on and did not download the plugin - which I had to compile and copy manually into ~/.synergy/plugins/

Now it's working fine.

**Comment by Silarn** [comment] 2015-05-27 15:25
I was having this issue - and you have to make sure the new ns plugin downloads successfully. Make sure the server is not running and go through the setup wizard, and make sure it installs correctly at the end.

On the other hand, I just tried to run the update on a freshly upgraded Fedora 22 install, and the wizard was unable to determine 'what type' of Linux I was on and did not download the plugin - which I had to compile and copy manually into ~/.synergy/plugins/

Now it's working fine.

**Comment by stockmaster** [comment] 2015-05-27 15:30
I followed your sugestions. 
Service Stoped
Reran The wizzard, Plugin installed propperlly:

Errors.

INFO: service command updated
INFO: starting new process
activeDesktop:Winlogon
INFO: starting new process
INFO: drag and drop enabled
ERROR: failed to get desktop path, no drop target available, error=2
NOTE: started server, waiting for clients
INFO: watchdog status: ok
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: stopped server
WARNING: detected application not running, pid=4072
INFO: backing off, wait=2s, failures=1
INFO: watchdog status: error
INFO: starting new process
activeDesktop:Default
INFO: starting new process
INFO: drag and drop enabled
NOTE: started server, waiting for clients
INFO: watchdog status: ok
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
INFO: accepted secure socket
INFO: service command updated
NOTE: new client disconnected
NOTE: accepted client connection
INFO: process started but command is empty, shutting down
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
INFO: got ipc shutdown message
NOTE: stopped server
INFO: process 5780 was shutdown gracefully
NOTE: starting server
NOTE: config file: C:/Users/STOCKM~1/AppData/Local/Temp/qt_temp.gq5580
NOTE: log level: INFO
INFO: service command updated
INFO: starting new process
activeDesktop:Default
INFO: starting new process
INFO: drag and drop enabled
NOTE: started server, waiting for clients
INFO: watchdog status: ok
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
INFO: accepted secure socket
NOTE: new client disconnected
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure

over and over and over again.
Client accepts the Fingerprint, still wont work.

**Comment by stockmaster** [comment] 2015-05-27 15:32
Of course synergy priocess gets a bit nutty on CPU usage

![image](https://cloud.githubusercontent.com/assets/4859025/7840180/fdd2cece-048d-11e5-9580-01059f7152e4.png)

**Comment by stockmaster** [comment] 2015-05-27 15:59
Ok, clearly this is not working. So question is, which is the latest build thats stable enough that can be used? and can one turn the SSL off all toghether? seems a bit of overkill for local Lan enviroment.

**Comment by Silarn** [comment] 2015-05-27 19:48
You should be able to disable SSL in the options. You'll have to disable it on all clients and the server and restart all of the connections.

**Comment by mfilipe** [comment] 2015-05-28 01:58
I have the same problem. My setup is Windows 8.1 Pro (Server) and Red Hat 6.5 (Client).

I disabled the SSL option and the communication works fine.

**Comment by ydellis** [comment] 2015-05-28 07:12
I have also the same problem. Server on Vista, Client on win 8.1 and XP.
Same half solution, disabled SSL and it is working.
Thank you for your suggestion.

**Comment by OmgImAlexis** [comment] 2015-05-28 07:30
Same here, windows 8.1 Pro as either server or client with SSL enabled and I get this, turn SSL off and no issues at all.
``ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call``

**Comment by mrsno** [comment] 2015-05-28 07:47
Same issue here with Debian sid as client and Fedora 20 as server. Fedora seems ok but Debian gives:

ERROR: ssl error occurred (generic failure)
ERROR: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
ERROR: failed to connect secure socket

This is after stopping the server and re-running the Wizard. Both client / server appear to have libns.so downloaded and a SSL folder in .synergy/

Turning off SSL on both makes it work (without SSL).

**Comment by stockmaster** [comment] 2015-05-28 11:03
yes i been using 1.7.3 for a full day now with SSL desiabled, no problems there. however i think this defeats the purpuse uh? lol

**Comment by gbirchmeier** [comment] 2015-05-28 14:31
I'm also seeing this today.  My plugin failed to download (it said a process was using it).  I tried to figure out how to make Synergy redownload the plugin, but was unsuccessful.  I tried deleting traces of previous Synergy installations and reinstalling, but I don't see that same download-plugin wizard that came up before.  I'm stumped.

**Comment by OmgImAlexis** [comment] 2015-05-28 14:34
I had to install it, then use the repair function of the installer, uninstall it using the installer and then reinstall it for it to show the plugins downloader. :-1: 

Worked fine on OSX though so it's definitely a bugged Windows version.

**Comment by gbirchmeier** [comment] 2015-05-28 14:41
@OmgImAlexis - that did not work for me.  I simply cannot make this mofo download a new SSL plugin.  Very frustrating.

**Comment by gbirchmeier** [comment] 2015-05-28 14:42
Ah, got it!  When I reran the configuration wizard, it finally redownloaded the plugin correctly.

**Comment by Silarn** [comment] 2015-05-28 16:38
I'm fairly sure this is all just a matter of needing the correct libns version downloaded. As I said, make sure the synergyc and synergys processes are not running before going through the wizard. Synergy on Windows runs a background process that handles switching users/admin state, so you may need to launch the task manager to make sure everything's stopped.

Then the wizard should be runnable within the GUI (File->Run Wizard). At the end of the setup it should download the new plugin version. If the message doesn't say it was successful, it's not going to work.

And of course, each machine needs to complete this process successfully.

If you're on linux and it wont download, you'll probably have to just build the release from source and copy the libns.so into your ~/.synergy/plugins/

**Comment by OmgImAlexis** [comment] 2015-05-28 16:40
@Silarn After I uninstalled Synergy I restarted my machine and made sure no processes from anything but the system were running and then reinstalled it, etc. and I've still got this issue.

**Comment by Silarn** [comment] 2015-05-28 16:42
Did the wizard say the ns plugin was installed successfully at the end of the wizard? If so, is it the same error in the log? If not, this is probably a different - though related - bug.

**Comment by OmgImAlexis** [comment] 2015-05-28 16:50
Yep, I'll try and reinstall it again tomorrow and see if I get it again, I'm wondering if something went weird with the installer download. I'll redownload it. It's 2AM here so I'm off to bed.

**Comment by gbirchmeier** [comment] 2015-05-28 17:33
For Windows users, I recommend this:

* Shut down all Synergy procs via Task Manager.
* Delete this dir and everything in it: c:\Users\your-name\AppData\Local\Synergy\
* Restart Synergy
* File->Run Wizard.  It should reinstall the NS plugin.
* Make sure the plugin install doesn't error out.

**Comment by the-wes** [comment] 2015-05-29 11:27
I imagine this will be fixed by including the plugin in the primary download, but if that isn't implemented by the time 1.7.4 is released, then this fix needs to be in 1.7.4. @speaker @nbolton

**Comment by stockmaster** [comment] 2015-05-30 02:27
Thank you

**Comment by sheddingmyskin** [comment] 2015-06-09 20:12
Just to confirm, everyone is downloading the new version on each server/client?  I got the error as well when I only installed the 1.7.3 on the server, but as soon as I did the client side install, it requested I confirm the fingerprint, and worked like a champ. **running Windows 7 Server/Ubuntu 14.04 Client/OSX 10.5 Client

**Comment by gbirchmeier** [comment] 2015-06-09 20:19
@sheddingmyskin - No, that is not related to the root cause of this issue.

**Comment by Silarn** [comment] 2015-06-09 20:24
I was under the impression you needed both server and client up to date, and a mismatch in nmcli versions would cause an issue. So this __is__ realated, but I think the problem is mostly stemming from the plugin, for one reason or another, not downloading and installing correctly.

**Comment by gbirchmeier** [comment] 2015-06-09 20:42
@Silarn @sheddingmyskin - A version mismatch is not the cause of this issue.  (I'll note that I *did* update both machines at the same time when I encountered this bug.)

The cause of this issue is that the NS plugin does not get updated properly.  (For me it was because Windows said the old version of the plugin in use and would not overwrite it with the new one, but I suppose there could be other reasons.)  Once this occurs, it's not obvious how to make Synergy retry the plugin update.

It doesn't matter what version the counterparty machine is running, because the bugged machine isn't setting up the socket correctly.  *The bugged machine is misbehaving before it even tries to connect.*

(Sure, a version mismatch would also probably fail to connect.  But that's a user error, and not this bug.)

**Comment by Silarn** [comment] 2015-06-09 20:49
@gbirchmeier t's technically a version mismatch of libns, but the causes are numerous. Either the process wasn't shut down, so the updater fails, the updater doesn't recognize the system type and so doesn't download the plugin, or one machine isn't updated (which isn't a bug, I accept, but causes the issue nonetheless). I'm sure there are other things that could potentially go wrong.

However it happens, there's a version mismatch, making the connection impossible and causing the above errors. From a non-user-error standpoint, including the plugins in the initial download would fix it. But I think the wizard needs to handle these update problems more gracefully, allowing the user to correct the issue more fluidly. Or detect the mismatch when trying to connect client/server and inform the user of the problem.

**Comment by gbirchmeier** [comment] 2015-06-09 21:14
Oh, you mean a version mismatch **of the plugin** (not of Synergy itself).  Yes, I agree there, and I agree that the installer needs to handle plugin-installation errors more gracefully.

I also agree that NS1 should be in the installer itself.  If everyone must download the plugin anyway, then why not bundle it in?  The decision to make it a separate download is kind of a headscratcher.

**Comment by Zapnologica** [comment] 2015-06-22 11:18
I am also having this error on synergy and cannot disable ssl as we have multiple synergy clients on the network.

**Comment by gbirchmeier** [comment] 2015-06-22 14:27
@Zapnologica If on Windows, try my fix instructions above -- see post that starts "For Windows users, I recommend this".

**Comment by ramasky9** [comment] 2015-06-25 20:41
Just to clarify a few steps in @gbirchmeier post "For Windows users, I recommend this:"

End all Synergy procs via Task Manager (under the Processes Tab).
Stop the Synergy service (Press Win+R and type "services.msc". Look for Synergy select Stop. Keep this window open.) 
Delete this dir and everything in it:  %LocalAppData%\Synergy\ (you won't lose your settings)
Open the Synergy program (from the Start menu, not the one in services)
Ignore any errors and File->Run Wizard. It *should* reinstall the NS plugin.
In the services window, start Synergy
On the client, accept fingerprint

**Comment by speaker** [comment] 2015-06-25 20:52
@ramasky9 Thank you for the clarification and update. I would, however, recommend that the service be stopped first, give it a moment to clean up. This should end the synergys application cleanly, which will in turn unhook synwinhk from other processes. Give this a few moments to cascade through before killing off the processes or there is a higher risk of errors related to synwinhk errors that require more drastic measures.

**Comment by ramasky9** [comment] 2015-06-26 18:06
Thanks Adam @speaker - that's a very good point. I've adjusted my post to reflect your suggestion.

**Comment by nbolton** [comment] 2015-07-25 00:31
Duplicates #4866

**Closed by nbolton** 2015-07-25 00:31 UTC
Labels: bug, priority-urgent
