### ISSUE TITLE
SSL connect error 'passive ssl error limit exceeded'

### ISSUE THREAD

**Issue by ambbell** [synergy/synergy#4750] opened 2015-06-02 15:35 UTC
I recently upgraded both my server (Linux - Ubuntu 14.04) and client (Windows - 7x64). I've never done anything special for configs beyond the basic setup. On the server I get this error when a client tries to connect:

```
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
INFO: client connection may not be secure
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
```

On the client I'm getting this error:
```
NOTE: connecting to service...
NOTE: connection established
ERROR: secure socket error: SSL_ERROR_SSL
ERROR: error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
ERROR: failed to accept secure socket
INFO: client connection may not be secure
INFO: accepted secure socket
NOTE: disconnected from server
NOTE: stopped client
WARNING: detected application not running, pid=269472
INFO: backing off, wait=2s, failures=1
INFO: starting new process
activeDesktop:Winlogon
INFO: starting new process
INFO: drag and drop enabled
ERROR: failed to get desktop path, no drop target available, error=2
```

**Comment by chriseng** [comment] 2015-06-02 21:01
Same issue. SSL broken since 1.7.3 with these error messagres. Win 8.1 x64 server. Win 7 x64 client.

**Comment by VeNoMouS** [comment] 2015-06-03 00:18
Check your libns.dll and libns.so 's are valid in the plugins dir, i had a case where the libns was corrupt... #4728

**Comment by DrOwl** [comment] 2015-06-03 13:15
I am having the same issue...
Server is using synergy-master-bd3a8e9-Linux-x86_64.deb
Client synergy-master-bd3a8e9-Windows-x86.msi

I have checked my servers libns.so..
~/.synergy/plugins$ file libns.so
libns.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1873e1c875ad61a0f7f6dd974f5c55dcd8a8a4ed, not stripped
~/.synergy/plugins$ md5sum libns.so
e6e576180ca96a54f71d19b064e29946  libns.so


Seems my problem is that the Windows installed did not download the plugin as I can not find  libns.dll

**Comment by DrOwl** [comment] 2015-06-03 14:04
Yes that is verified, I manually downloaded the windows ns.dll and created the plugin's dir and the "ERROR: passive ssl error limit exceeded: 100001" has been resolved.

It would appear that the Synergy Server is not checking if the incoming connection is secure or not

**Comment by Criggie** [comment] 2015-06-03 20:52
Same here, using 1.7.3 on an old imac and a debian linux box.  The quick workaround is to untick "[_] Use SSL encryption (unique certificate)" under preferences on the client, AND to run the server without "--enable-crypto"   Note there is no matching "--disable-crypto" 

Of course only do this on networks you trust etc.

**Comment by VeNoMouS** [comment] 2015-06-04 01:28
@DrOwl so... exactly what i said in #4728 then? :P

**Comment by PinkFrosty** [comment] 2015-06-04 18:54
I just upgraded to 1.7.3 today.  The server is a MAC running OS X 10.10.4  The client is my Dell laptop running Debian 8. I've used encryption for a long time with no issues but after 3 hours I started seeing the error below.  I have to disable SSL on both machines and everything works fine again.  Both machines are registered and downloaded the plugin.  I'm on a secure network but prefer to use encryption.

Server:
Darwin XXXX 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
Client:
Linux XXXXX 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

ERROR:
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to accept secure socket
INFO: client connection may not be secure
NOTE: accepted client connection
ERROR: passive ssl error limit exceeded: 100001

**Comment by dashaun** [comment] 2015-06-05 16:20
Same issue:
Just upgraded 2 64-bit Ubuntu machines and 1 OSX 10.10 laptop, to 1.7.3.  Nothing worked, only saw the passive ssl error limit exceeded: 100001 error.

Disabled SSL on all machines and now I'm working.  Thank you @PinkFrosty for the tip!

**Comment by chriseng** [comment] 2015-06-08 18:55
I give up. I've tried re-running the wizard, uninstalling/reinstalling, nothing works. This is a pain. I downgraded to 1.7.2 and SSL works again.

**Comment by dragonivre** [comment] 2015-06-09 03:34
Running Ubuntu 14.04.2 LTS with Codename trusty as a server with a Mac OS X 10.10.3 as a client and kept getting error error on the Mac

WARNING: failed to connect to server: serv
er is not responding
NOTE: connecting to 'xx.xx.xxx.xxx': xx.xx.xxx.xxx:24800
ERROR: passive ssl error limit exceeded: 100001
ERROR: fa
iled to connect secure socket
NOTE: disconnected from server
NOTE: stopping synergy desktop process

**Comment by python138** [comment] 2015-06-09 18:38
Same error - Centos 6.6 server (with dpkg workaround), OSX 10.10.3 client, ssl enabled. 
I'm good for a few hours, and then I get this - 

ERROR: passive ssl error limit exceeded: 100001

I transition a fair amount, and use the client (OSX) more frequently, so its probably generating a good deal of ssl traffic. 

This requires restarting the server (centos 6.6) in order to resume the connection.

**Comment by sheddingmyskin** [comment] 2015-06-09 20:13
Just to confirm, everyone is downloading the new version on each server/client? I got the error as well when I only installed the 1.7.3 on the server, but as soon as I did the client side install, it requested I confirm the fingerprint, and worked like a champ. **running Windows 7 Server/Ubuntu 14.04 Client/OSX 10.5 Client

**Comment by python138** [comment] 2015-06-09 20:30
Confirmed 1.7.3 on both client/server, and it downloaded a fresh ns plugin.

**Comment by akurei** [comment] 2015-06-09 20:30
@sheddingmyskin Correct. 1.7.3 on Arch Linux x86_64 (Client) and 1.7.3. on Windows 8.1 64bit (Server).

**Comment by stornado** [comment] 2015-06-10 01:26
我用的synergy-v1.7.3-stable-efd0108-Windows-x86.msi在windows8.1 64作为服务端，在windows7 64作为客户端就报“ERROR: failed to accept secure socket”，都换成synergy-v1.7.3-stable-efd0108-Windows-x86.msi就好了

**Comment by acook** [comment] 2015-06-10 05:47
Same problem, but after unchecking the SSL checkbox on both client and server now they can't find each other at all, and the client keeps trying to reinstall Bonjour. This release is very broken.

**Comment by PinkFrosty** [comment] 2015-06-10 17:32
Yes I downloaded the plugin when I installed it on both machines.  I even uninstalled, installed an older version then installed the new version again.  (Downloading the plugin for the second time.)  It works for a while then starts to encounter the error.  Also, with SSL disabled on both machines the client (Debian 8.1) just stops working and I have to restart it.  I went to back 1.6.2.  It has some cut & paste issues but thats better than the dropped connections.

**Comment by egmik3** [comment] 2015-06-11 14:29
I am having this same issue on 1.7.3 using windows 8 64bit and Mac OSX 10.10.3  .  Is there a fix for this?

**Comment by jml674** [comment] 2015-06-12 17:17
had same issue with windows7 client and windows8 server config. Tried to clean up and reinstall with no progress. Finally unchecked SSL on server (only) and it works.

**Comment by shadda** [comment] 2015-06-12 23:51
Same issue, win7 server, osx 10.10 client

**Comment by jml674** [comment] 2015-06-13 09:35
just noticed that if client is restarted then SSL needs to be de-activated on client side also.

**Comment by kapnkirk** [comment] 2015-06-15 19:21
Same problem for me: W7 Pro x64 server; Ubuntu 14.04.2 client
unchecking SSL does NOT fix for me; worked great before upgrade

**Comment by cormickjbrowne** [comment] 2015-06-17 18:28
I'm getting this error as well.
Server: OS X 10.10.2
Client: OS X 10.10.2

I don't see an option to "uncheck SSL".

**Comment by python138** [comment] 2015-06-17 18:38
On mac, with synergy in foreground, 
Synergy - Preferences - Encryption, uncheck Enable

SSL (secure sockets layer) is the encryption protocol.

**Comment by davidmmiller** [comment] 2015-06-18 16:32
This got labeled "enhancement".  This is *not* an enhancement.  This is a "bug".

I am running 1.7.3 on Win7 server and Ubuntu 14.04 client with SSL and v1.7.3 has been horrific to use since I upgraded to it.

When starting client I get initial messages re: passive ssl error and client stops.  If I then select start in client it will connect and work for a while and then lose connection.

# Server Win7
NOTE: accepted client connection
ERROR: ssl error occurred (system call failure)
ERROR: failed to accept secure socket
NOTE: accepted client connection
NOTE: client "l8b9eaa" has connected

# Client Ubuntu 14.04
NOTE: starting client
NOTE: config file: /tmp/qt_temp.TJ3573
NOTE: log level: NOTE
NOTE: started client
NOTE: connecting to 'X.X.X.X': X.X.X.X:24800
ERROR: passive ssl error limit exceeded: 100001
ERROR: failed to connect secure socket
NOTE: disconnected from server
NOTE: stopped client
NOTE: stopping synergy desktop process
NOTE: starting client
NOTE: config file: /tmp/qt_temp.XM3573
NOTE: log level: NOTE
NOTE: started client
NOTE: connecting to 'X.X.X.X': X.X.X.X:24800
NOTE: server fingerprint: 0E:10:3A:8C:B9:3A:F1:B5:29:2C:D6:6B:B3:E9:17:1E:6E:84:29:DF
NOTE: connected to server

**Comment by python138** [comment] 2015-06-18 17:03
Yeah, SSL transport crashing isn't an enhancement. 

Downgrading to 1.6.2 seems to work for me with Windows 7 <-> Centos 6.6 <-> OSX 10.10
Atleast I dont get the passive SSL error.

**Comment by darkdragon-001** [comment] 2015-06-19 14:57
Same problem here!

I got it working by manually deleting and reinstalling (or upgrading?) the ns plugin.
On Windows, I had to manually stop the service to be able to delete the ns plugin file, start the service again, run synergy, run wizard (downloads ns plugin).

**Comment by darkdragon-001** [comment] 2015-06-19 15:17
But it still seems that the daemon version is still broken.

Running `synergyc IP` on my Ubuntu 15.04 still results in the error above. Starting from GUI works after manually upgrading the plugin...

**Comment by darkdragon-001** [comment] 2015-06-19 16:49
Make sure that the ns plugin is installed for every user who wants to run synergy!
Check if your synergy is started e.g. by root account (startup script). Then this account needs the plugin as well!

**Comment by darkdragon-001** [comment] 2015-06-22 08:39
I think the problem lies in the plugin upgrading:
When I first tried to (automatically) upgrade - first start after upgrade to 1.7.3 - there was a permission error which was existent because the Synergy service on Windows was running and locking the DLL.

Maybe you should stop Synergy service on Windows before writing plugins.

**Comment by speaker** [comment] 2015-06-23 22:18
Opened #4823 to deal with the plugin install issue.

**Comment by amerry** [comment] 2015-06-24 12:35
I'm getting this issue about 80% of the times I try to connect. If I repeatedly hit "Start" in the GUI, it will eventually connect, but most attempts display the "passive ssl error limit exceeded: 100001" error and disconnect from the server.

It also occasionally spontaneously disconnects, usually when I have the screens locked while I go for lunch, but that may be unrelated (it's sometimes a client crash, and sometimes "server is dead", even though the server appears to still be running, and can be reconnected to).

**Comment by samrocketman** [comment] 2015-06-24 15:03
My client crashes from Windows (server) -> Mac (client) nearly every time.  I had to disable encryption entirely because it was not use-able.

**Comment by davidmmiller** [comment] 2015-06-24 16:49
Agree with @amerry locking screens and walking away for 10+ minutes has resulted in passive ssl error limit exceeded very regularly.

Logs don't have timestamps, so I can't be precise as to when this actually occurs. See issue #4312

**Comment by speaker** [comment] 2015-06-25 17:13
@samrocketman @davidmmiller @amerry @python138 
I've pushed a change that addresses the Passive SSL limit issue specific to connect and accept operations.Searching for "9dc0a1d" in the nightly builds should return builds that contain the fix. One is from my sandbox, which is pretty clean, and another from master.

This will not address cases where the disconnect and reconnect happen so fast that the client is trying to reconnect before the server is still cleaning up. (Usually only happens when the Accept button is pressed on a client, and then the 2nd press will connect successfully.)

This is based off of 1.7.4 code, so depending on the OS, you might not even have to run the wizard again to get the new plugin (yay! symbolic links!)

**Comment by samrocketman** [comment] 2015-06-25 18:00
Great news; is there a way I can test it? @speaker

**Comment by speaker** [comment] 2015-06-25 18:10
@samrocketman Try this link: http://synergy-project.org/nightly?filter=9dc0a1d it will pull up both sandbox and master builds. The process of getting the files onto the ftp server might take a bit longer, so if you want the master branch builds, give it a little longer.

**Comment by samrocketman** [comment] 2015-06-26 02:57
@speaker thanks for the link.  I'll bring my Mac home tomorrow and test it.

**Comment by satanicpuppy** [comment] 2015-06-30 14:51
Fixed mine by uninstalling/reinstalling the Windows plugin.

**Comment by samrocketman** [comment] 2015-06-30 17:09
@satanicpuppy how to uninstall/reinstall the Windows plugin?  I know how to uninstall/reinstall the whole software.  But I couldn't find any kind of plugin manager.

**Comment by darkdragon-001** [comment] 2015-06-30 18:12
@samrocketman  delete plugin in folder and then run wizard again.

**Comment by vadi2** [comment] 2015-06-30 22:27
The fix didn't work for me. I had the same error on both the server (ubuntu 14.04) and the client (windows 7). Installed the nightly builds on both using the link above, deleted plugins folder on client, re-ran wizard - now client just spams:

```
INFO: connecting to '10.1.1.4': 10.1.1.4:24800
INFO: OpenSSL 1.0.2 22 Jan 2015
WARNING: failed to connect to server: Connection was refused
```

The server doesn't see anything, just says "waiting for clients".

It's not my firewall as prior to upgrading Synergy, I had to configure it to allow incoming 24800 ports and it was working.

**Comment by padraigdoran** [comment] 2015-07-01 09:17
I'm on synergy-v1.7.4-stable-44fa44f for Windows/Ubuntu x64 and it I get the Passive SSL Error. This is with a clean install.

**Comment by keyvanfatehi** [comment] 2015-07-01 19:47
i get this too

**Comment by padraigdoran** [comment] 2015-07-02 08:14
If I click connect from the client 3 or 4 times, it connects but eventually comes up with the error limit exceeded message on the client.

**Closed** 2015-07-10 21:05 UTC
Labels: bug

**Comment by padraigdoran** [comment] 2015-07-13 13:56
Now works for me with synergy-v1.7.4-stable-cbd63e9 compiled versions

**Comment by XinyuHou** [comment] 2015-07-14 17:24
Could anyone test this nightly?

http://synergy-project.org/nightly?filter=2de27

**Comment by davidmmiller** [comment] 2015-07-16 20:49
Nightly 2de27 Windows 64 package (upgraded over top of nightly 9dc0a1d) won't start on Win7 (64bit).

Closing the Windows error results in a repeat attempt to launch and failure every time.

####
Synergygs.exe has stopped working.

Problem signature:
  Problem Event Name:	BEX64
  Application Name:	synergys.exe
  Application Version:	0.0.0.0
  Application Timestamp:	55a42066
  Fault Module Name:	synergys.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	55a42066
  Exception Offset:	000000000007f808
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	3048
  Additional Information 2:	3048cf69c803a8eadaa95f7f2b16f36e
  Additional Information 3:	7fbc
  Additional Information 4:	7fbcf73e8608e5c4fe92111f7ed7fda2
####

Log:
[2015-07-16T16:34:50] INFO: using last known command: "C:/Program Files/Synergy/synergys.exe" -f --no-tray --debug INFO --name z123456 --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir "C:\Users\UserName\AppData\Local" -c "C:/Users/UserName/AppData/Local/Temp/qt_temp.Hp7312" --address :24800
[2015-07-16T16:34:50] INFO: service command updated
[2015-07-16T16:34:50] INFO: starting new process
[2015-07-16T16:34:55] INFO: activeDesktop:Winlogon
[2015-07-16T16:34:55] INFO: starting new process
[2015-07-16T16:34:56] INFO: drag and drop enabled
[2015-07-16T16:35:04] WARNING: detected application not running, pid=2164
[2015-07-16T16:35:05] INFO: backing off, wait=2s, failures=1
[2015-07-16T16:35:07] INFO: starting new process
[2015-07-16T16:35:07] INFO: activeDesktop:Winlogon
[2015-07-16T16:35:07] INFO: starting new process
[2015-07-16T16:35:07] INFO: drag and drop enabled
[2015-07-16T16:35:08] ERROR: failed to launch, error: process immediately stopped
[2015-07-16T16:35:08] INFO: backing off, wait=4s, failures=2
[2015-07-16T16:35:12] INFO: starting new process
[2015-07-16T16:35:12] INFO: activeDesktop:Winlogon
[2015-07-16T16:35:12] INFO: starting new process
[2015-07-16T16:35:12] INFO: drag and drop enabled
[2015-07-16T16:35:13] ERROR: failed to launch, error: process immediately stopped
[2015-07-16T16:35:13] INFO: backing off, wait=6s, failures=3
[2015-07-16T16:35:19] INFO: starting new process
[2015-07-16T16:35:19] INFO: activeDesktop:Winlogon
[2015-07-16T16:35:19] INFO: starting new process
[2015-07-16T16:35:19] INFO: drag and drop enabled
[2015-07-16T16:35:20] ERROR: failed to launch, error: process immediately stopped
[2015-07-16T16:35:20] INFO: backing off, wait=8s, failures=4

**Comment by davidmmiller** [comment] 2015-07-16 21:17
Full uninstall and then reinstall of Win64 package on Win7 gets service started, then connection from Ubuntu client running nightly 2de276c crashed synergygs.exe.  Trying to restart on server results in:

[2015-07-16T17:12:25] INFO: starting server
[2015-07-16T17:12:25] INFO: config file: C:/Users/UserName/AppData/Local/Temp/qt_temp.gq2372
[2015-07-16T17:12:25] INFO: log level: WARNING
[2015-07-16T17:12:26] INFO: activeDesktop:Default
[2015-07-16T17:12:26] ERROR: failed to init synwinhk.dll, another program may be using it
[2015-07-16T17:12:26] FATAL: failed to start server: unable to open screen
[2015-07-16T17:12:27] ERROR: failed to launch, error: process immediately stopped
[2015-07-16T17:12:29] INFO: activeDesktop:Default
[2015-07-16T17:12:29] ERROR: failed to init synwinhk.dll, another program may be using it
[2015-07-16T17:12:29] FATAL: failed to start server: unable to open screen
[2015-07-16T17:12:30] ERROR: failed to launch, error: process immediately stopped
[2015-07-16T17:12:34] INFO: activeDesktop:Default
[2015-07-16T17:12:34] ERROR: failed to init synwinhk.dll, another program may be using it
[2015-07-16T17:12:34] FATAL: failed to start server: unable to open screen
[2015-07-16T17:12:35] ERROR: failed to launch, error: process immediately stopped

**Comment by padraigdoran** [comment] 2015-07-17 09:10
@davidmmiller I was getting this error too. I solved it by breaking all file handles to C:\Program Files\Synergy\synwinhk.dll using the Unlocker program and restarted. I think I had to use Unlocker twice for it to get started up properly. I've had no problems with it since.

**Comment by ColinAnthony** [comment] 2015-08-06 08:37
Ubuntu14.04 and Win7(as server) with Synergy 1.73pro on both.
Same issue as above. Deleting the plugin folder on the windows machine and re-running the setup wizard fixed the ssl error

**Comment by AaronLS** [comment] 2015-08-10 14:47
Have the same issue, I cannot find a plugins folder though.  Where is it on Windows?  Are we talking about the OpenSSL folder under Program Files/Synergy?

**Comment by ColinAnthony** [comment] 2015-08-10 15:15
For future reference, the folder you are looking for is under: users/<username>/AppData/local/Synergy
