### ISSUE TITLE
Cursor won't transfer from server-> client with image on clipboard

### ISSUE THREAD

**Issue by ajholt** [synergy/synergy#4678] opened 2015-05-15 16:09 UTC
After taking a screenshot on my Windows 7 Synergy server, I was unable to move my mouse to my Mac client. The cursor would lock at the edge of the screen of the client where it was coming over, but would not transfer control of either the mouse or the keyboard. It appears that the issue was somewhere around converting the bitmap image -- once I copied some plain text back into the clipboard, everything again worked as inspected.

The Synergy console on the server shows this message every time I try to move from server to client:

INFO: bitmap: 1280x1024 32
INFO: convert image from: depth=32 comp=3

**Comment by ambbell** [comment] 2015-05-15 16:34
Sounds like a duplicate of #4601

**Comment by nbolton** [comment] 2015-05-16 09:41
Duplicates #4601

**Closed by nbolton** 2015-05-16 09:41 UTC
