### ISSUE TITLE
Memory leak / linux client 1.7.2

### ISSUE THREAD

**Issue by cmellwig** [synergy/synergy#4656] opened 2015-05-11 22:19 UTC
The memory leak I've reported in #4363 still persists in version 1.7.2
Linux T20 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux

synergyc uses up ~12GB RAM before the machine freezes.

```
May 11 23:55:30 T20 kernel: [22747]  1000 22747  3003309  2962937    5834      14        0             0 synergyc
```
```
May 11 23:55:30 T20 kernel: Out of memory: Kill process 22747 (synergyc) score 726 or sacrifice child
May 11 23:55:30 T20 kernel: Killed process 22747 (synergyc) total-vm:12013236kB, anon-rss:11851748kB, file-rss:0kB
```

**Comment by VeNoMouS** [comment] 2015-05-12 09:42
haven't experienced this myself... but i use synergy as a server on linux...

**Comment by speaker** [comment] 2015-06-15 17:04
This does appear to be a duplicate of #4363

**Closed by speaker** 2015-06-15 17:04 UTC
Labels: bug, v1.7
