### ISSUE TITLE
Windows 10 Server/OSX Client Extreme Lag

### ISSUE THREAD

**Issue by orbv** [synergy/synergy#5156] opened 2015-12-15 15:18 UTC
Using Synergy 1.7.5 - Windows 10 server and OSX El Capitan client.
Synergy may work fine on the client for a few minutes, then the mouse will lag horribly. I can still use it if I move the mouse very slowly. If I move the mouse at a normal speed it will lag behind and eventually disconnect. At that point, the GUI on Windows 10 will stop responding.

CPU usage from Synergy on the client is about 30% when the mouse is on the client side.

Pings to the client from the server:

    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64
    Reply from 192.168.1.77: bytes=32 time<1ms TTL=64

Once the client loses connection, the information window (on the client) outputs:

    NOTE: server is dead
    WARNING: failed to connect to server: server is not responding

I am really not sure how to perform any other helpful debugging. Let me know what I can do to gather more information.

**Comment by mrconnerton** [comment] 2015-12-16 20:00
I'm experiencing this as well and this is likely a duplicate of https://github.com/synergy/synergy/issues/4911

**Comment by XinyuHou** [comment] 2015-12-21 20:20
@orbv 
Are you using WIFI or Ethernet?

Please also check if you have any big data in your clipboard.

I will close this issue for now.

**Closed by XinyuHou** 2015-12-21 20:20 UTC

**Comment by mrconnerton** [comment] 2015-12-21 20:22
I am running via wifi  (ubuntu server, win 10 client) and no big data in clipboard.

**Comment by orbv** [comment] 2015-12-21 20:23
I am running via wired ethernet. I have monitored the traffic via WireShark and see no apparent issues on the network. I do not have any data on the clipboard. I have tried several reboots, router reboots, etc.

**Comment by XinyuHou** [comment] 2015-12-21 20:29
@mrconnerton @orbv 
Please leave any comment in #4911

**Comment by barocsi** [comment] 2016-05-04 12:34
#5316

**Comment by kenyob** [comment] 2016-07-13 15:27
Its a little laggy now for me.
Running Windows 10 Server (Wired)
Mac OSX El Capitan (10.11.5) Client (Wireless)

I also keep getting WARNING: cursor may not be visible moving between the screens.
