### ISSUE TITLE
SSL_ERROR_SSL (unknown alert type) on Windows 8.1 client

### ISSUE THREAD

**Issue by JoshMcCullough** [synergy/synergy#4409] opened 2015-03-05 19:46 UTC
Version: 1.7.0-master-2feb916 (beta)

Win7 Server; Win8.1 Client

After installing and running the wizard for `1.7.0-master-2feb916`, I have SSL enabled, which seems to work fine on the server (Win7). On the client (Win8.1), I've enabled SSL but I'm not able to control the service from the desktop app. This comes up when I click start, get the "Synergy is starting" message, and then get impatient and click stop:

   ERROR: could not get session id for process id 121284
   ERROR: secure socket error: SSL_ERROR_SSL
   ERROR: secure socket error: error:140940F6:SSL routines:ssl3_read_bytes:unknown alert type

Note that during this time, mouse/keyboard interactivity between the machines works fine (so Synergy is definitely running). Once I click stop, it does stop Synergy. The app just can't seem to start it.

**Comment by nbolton** [comment] 2015-03-06 11:51
@JoshMcCullough Thanks for raising this, please let me know if you spot any more bugs in the beta. Much appreciated!

**Comment by nbolton** [comment] 2015-03-06 11:51
@XinyuHou

**Comment by XinyuHou** [comment] 2015-03-18 14:43
I need to dig into the error unknown alert type then report back.

**Comment by XinyuHou** [comment] 2015-03-18 14:54
@JoshMcCullough  

- The app just can't seem to start it
Do you mean when you click start button in GUI nothing happens?

- I'm not able to control the service from the desktop app
Do you see this in your logging?

NOTE: connecting to service...
NOTE: connection established

Is Synergy service running on your machine?
You can check it by doing:
1. Win+r
2. type in services.msc
3. find Synergy
4. check status column

**Comment by nbolton** [comment] 2015-04-15 14:20
Maybe fixed by 916a4c75af19f9d6031c7236d63b308f943250fc

**Comment by JoshMcCullough** [comment] 2015-04-15 14:25
Sorry didn't see the comment from @XinyuHou.

Stuff happens when I click the start button, it just simply does not start the service...like it is stuck on some communication error.

All I see in the log, IIRC, is that "Synergy is starting...".

Synergy service was running as I was using the service snap-in to start/stop it since the Synergy desktop app wasn't able to do it.

**Comment by nbolton** [comment] 2015-04-15 17:27
@JoshMcCullough I think this is a separate issue, not related to `SSL_ERROR_SSL` - would you mind raising another bug? Generally the service has been quite unstable for me recently though I haven't figured out any specific repro steps.

**Comment by XinyuHou** [comment] 2015-04-20 16:32
@JoshMcCullough 
I can't find the cause of this error, "SSL routines:ssl3_read_bytes:unknown alert type". This may be fixed by 916a4c75af19f9d6031c7236d63b308f943250fc as @nbolton said. Could you try the latest nightly? Here is the link: http://synergy-project.org/nightly?filter=2a2d095

> Stuff happens when I click the start button, it just simply does not start the service
If you mean Synergy GUI doesn't start the process, it is probably caused by Synergy service crashed or some general error that should be shown in log window.

As you found out, Synergy GUI has no control of toggling the Synergy service.

**Closed** 2015-04-20 17:27 UTC
Labels: bug

**Comment by XinyuHou** [comment] 2015-04-20 17:30
@JoshMcCullough 
Sorry, my bad. 916a4c7 is not ready for test. We need to update the plugins on our server side. I will let you know when it is ready.

**Comment by nbolton** [comment] 2015-04-21 22:17
Ready now!

On Monday, April 20, 2015, Xinyu Hou <notifications@github.com> wrote:

> @JoshMcCullough <https://github.com/JoshMcCullough>
> Sorry, my bad. 916a4c7
> <https://github.com/synergy/synergy/commit/916a4c75af19f9d6031c7236d63b308f943250fc>
> is not ready for test. We need to update the plugins on our server side. I
> will let you know when it is ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/synergy/synergy/issues/4409#issuecomment-94517123>.
>


-- 
--
Nick Bolton
Founder & CEO
<http://synergy-project.org/>
 +1 650-265-2044
 +44 (0)20 3598 3068

*Synergy:* Be more seamless
