### ISSUE TITLE
multiple monitor support

### ISSUE THREAD

**Issue by the-wes** [synergy/synergy#4292] opened 2014-12-23 18:27 UTC
Synergy sees all monitors plugged in to a single computer as one large "screen" - adding together dimensions in the direction the monitors are oriented and using the longest of the other dimension. This causes problems like dead zones and edges which can't be used to switch.

Other input sharing software does this better.

**Comment by beporter** [comment] 2015-01-02 02:07
@the-wes This is a duplicate of #3744, by the way, which has a lot of other linked issues and a ton more detailed information in it.

**Comment by beporter** [comment] 2015-01-02 02:12
Personally, I feel like when multiple screens on a single system are arranged perpendicular to the switching edge (arranged as a "long line" of monitors), only the "closest" screens' dimensions should be used during the cross over. When multiple screens are arrange parallel to the switching edge (in a ""T formation, or a 2x2 grid for example), then the sum of the "closest" screens' dimensions should be used.

It's also worth nothing that the old config file syntax would be highly compatible with this, since you could still simulate an "L" configuration using a `left:50,100` entry to only switch to the "top" screen on the other system. This admittedly is hard to visualize without graphics, which I'd be happy to whip up if it'd help, but I suspect the core devs have a good enough mental model of how the software works to understand.

**Comment by nbolton** [comment] 2015-01-03 10:46
Duplicates #3744

**Closed by nbolton** 2015-01-03 10:46 UTC
Labels: enhancement
