### ISSUE TITLE
Client Dies on Ubuntu

### ISSUE THREAD

**Issue by pak101** [synergy/synergy#4710] opened 2015-05-26 07:30 UTC
![screen shot 2015-05-26 at 12 53 56 pm](https://cloud.githubusercontent.com/assets/5019785/7807200/ff40e8f0-03a6-11e5-8972-b2ba018c6eb9.jpg)

Upgraded 1.7.2 recently on my Server (Mac 10.10.3) and my client (Ubuntu 12.10). My client died unexpectedly, attached screenshot and this the error on the client machine:

NOTE: connected to server
INFO: entering screen
INFO: leaving screen
INFO: entering screen
INFO: leaving screen
INFO: entering screen
INFO: leaving screen
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  19 (X_DeleteProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  4395
  Current serial number in output stream:  4395
NOTE: stopping synergy desktop process

**Comment by marvins** [comment] 2015-05-26 20:57
I bet its related to my bug report.  Check the output log on the client. 
https://github.com/synergy/synergy/issues/4631

**Comment by speaker** [comment] 2015-06-16 16:19
Duplicate of #4740

**Closed by speaker** 2015-06-16 16:19 UTC
