### ISSUE TITLE
Synergy loses connection for no apparent reason

### ISSUE THREAD

**Issue by andyfinity** [synergy/synergy#5057] opened 2015-10-08 19:10 UTC
My problem involves Synergy simply losing its connection. I don't see anything obviously wrong in the logs, but I've included links to (slightly abridged versions of) DEBUG2 logs in case somebody wants to look at it. This problem appears every few minutes, rendering Synergy pretty much broken. Simply clicking "Apply" on the client will resume the connection and I can use it again for another few minutes.

I'm using two Linux boxes (Fedora 22, master, and Ubuntu 15.04, slave) and connected them through a gigabit switch. I'd be happy to post more details as requested.

Edit: Synergy version is 1.7.4 on both client and server.

Server log: http://pastebin.com/u4pJQiqF
Client log: http://pastebin.com/N9jgtkUV

**Comment by miraculixx** [comment] 2015-10-10 19:26
+1 same issue here. possible duplicate of #4949 and a few others pointing in that direction (problems started with 1.7.4). synergy used to work rock solid for the last 4-5 years, so not sure what happened?

**Comment by andyrussell** [comment] 2015-10-11 03:37
It is a strange problem, to be sure. There are definitely others out there with similar problems, but each seems to behave a little differently. For example in the bug you referenced, OP sees lots of "client is already connected" messages, whereas I don't see those in my logs. Others in the comments have problems closer to mine, but I'm not yet convinced they're totally identical.

For now I guess I'll just revert to 1.7.3 or older and see what happens.

**Comment by joubertredrat** [comment] 2015-10-12 23:19
I don't know if my problem is same, but, I simple lose connection too, but is on server, if I restart on gui, return to work normally. I will get log to put here too.

**Comment by hpcadv** [comment] 2015-10-13 20:04
I am using Fedora 18 as the server and Mint 17 as the client.  I installed synergy 1.7.4 today after running flawlessly on 1.5 for a long while.  After reading these forums I discovered that the disconnection was occurring because of a clipboard update while using an encrypted synergy session.  While moving from the client to the server I would get a disconnect and have to restart both services but would quickly loose connection again if I made any changes to the client clipboard.  Once I reconnected without encryption the problem seems to have vaporized.  Cake or Death!  Security or Stability!

**Comment by andyfinity** [comment] 2015-10-13 20:43
Wow, that's quite an update (1.5 -> 1.7.4). I'm not using encryption, so I'd guess that our problems are different. Regardless, everybody's problems seem to have been a regression in either 1.7.3 or 1.7.4. I dropped back to 1.7.1 and am experiencing no problems.

Kudos on tolerating Fedora 18 for so long!

**Comment by hpcadv** [comment] 2015-10-13 20:48
Hahaha...  312 days uptime...  when it dies I will upgrade...

**Comment by XinyuHou** [comment] 2015-10-21 17:31
Duplicate to #4949

**Closed by XinyuHou** 2015-10-21 17:31 UTC
