### ISSUE TITLE
Unable to accent letters on client with "shift + accent" then letter

### ISSUE THREAD

**Issue by pandre45** [synergy/synergy#4293] opened 2014-12-25 22:16 UTC
My keyboard is Brazilian-Portuguese ABNT2. I am able to produce any accented letter on server but on client only those accents those that do not require the pressing of the shift key.

**Comment by nbolton** [comment] 2015-01-30 11:14
Thanks for contributing to Synergy, @pandre45. Unfortunately it's a little tricky for me to triage this bug report because there seems to be some info missing.

Please could you write numbered steps to reproduce the problem, let me know what operating systems you're using (including version numbers), and also what versions of Synergy you're using.

I'm going to close this issue because normally people don't take time to revise their issue, but I am now following the issue so just let me know when I can reopen it. Thanks!

**Closed by nbolton** 2015-01-30 11:14 UTC

**Comment by shamisen** [comment] 2015-01-30 15:56
Dear @nbolton, I'm also having the same issue reported by @pandre45. I'm running Synergy 1.6.2 as a server in Ubuntu 10.10 and as a client in Windows 7 Home Premium.

I'm also using a Brazilian-Portuguese ABNT2 keyboard (both the client and server are configured to the appropriated keyboard). To add some context, these keyboards have the following layout:
![keyboard layout](https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/KB_Portuguese_Brazil.svg/900px-KB_Portuguese_Brazil.svg.png)

These are the steps to reproduce the bug:
1 - Start Synergy normally. 
2 - Open any text field in the server and the client.
3 - When the mouse is in the server, if you press **Shift+´** (the key in red at the right of 'P' key in the layout image) followed by **space**, **a**,**e**,**i**,**o** or **u** it writes **`**,**à**,**è**,**ì**,**ò** or **ù** respectively, which is the expected behavior. However, if you do the same when the mouse is in the client, it only writes **space**, **a**,**e**,**i**,**o** or **u**, respectively. 
4 - The same behavior happens with **Shift+~**, but with the **^** accent.

If more information is needed, I'd be very happy to provide. Thanks for developing Synergy and for your solicitude in catching the bugs :)

**Comment by robsoncombr** [comment] 2015-07-24 12:32
Shouldn't this be re-opened? @shamisen explanation is pretty good and the problem really exists. Thank you.

**Comment by zcrayfish** [comment] 2015-10-01 17:36
+1, this issue still exists.
