### ISSUE TITLE
Latvian apostrophe layout doesn't work properly

### ISSUE THREAD

**Issue by zingmars** [synergy/synergy#4302] opened 2015-01-03 10:29 UTC
The Latvian apostrophe layout requires one to press the apostrophe character (') and a letter, which will result (depending on the letter) in either a macron (āēīūō), a cedilla (ķļ...) or a caron (čž...) being written.

If the host is a Linux machine, and a client - Windows machine, then the windows machine won't type neither apostrophes, or handle the writing of the diacritic characters. If both the client and the host runs on Windows with said layout, it will work only partially - you can type the apostrophe, and cedilla/caron  characters work, but for some reason you can't type characters with a macron.  (Host/Client) Linux/Linux combo works just fine, and I did not test Windows/Linux combo.

Just a note for testing - Windows 8.1 comes with a Latvian (Standard) layout which is the apostrophe layout I'm using. For earlier versions of windows you need to download the layout here - 
http://laacz.lv/apostrofs/ (the big "Novelc apostrofu tūlīt pat »" button). It's effectively the same as the Windows layout, but was created long before Windows actually supported this layout.

**Comment by nbolton** [comment] 2015-01-30 11:34
Thanks for contributing to Synergy, @zingmars. Unfortunately it's a little tricky for me to triage this bug report because of the way its written.

Please could you write numbered steps to reproduce the problem? Also if you haven't done so, clearly write in a separate paragraph what operating systems you're using (including version numbers), and what versions of Synergy you're using.

I'm going to close this issue because normally people don't take time to revise their issue, but I am now following the issue so just let me know when I can reopen it. Thanks!

**Closed by nbolton** 2015-01-30 11:34 UTC

**Comment by zingmars** [comment] 2015-01-31 10:13
>Please could you write numbered steps to reproduce the problem?
Have two machines (in my case Linux host, Windows client), have both run synergy, have the Latvian keyboard layout on both of them, try to write stuff, run into the problem, it being the fact that the apostrophe key used for diacritics simply doesn't work on the client machine, even though the keyboard layouts on both machines (at least as far as I'm concerned) work identically. 

>Also if you haven't done so, clearly write in a separate paragraph what operating systems you're using (including version numbers), and what versions of Synergy you're using.
Okay, this was a month ago, so I don't remember the specific version of Synergy I was using (can't check right now), but it was the latest one from github (I compiled it on both machines). Like I mentioned earlier - It was a linux host (Linux Mint 17.1; 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux), and a Windows host (Windows 8.1).
