### ISSUE TITLE
GUI setting to disable drag and drop feature

### ISSUE THREAD

**Issue by the-wes** [synergy/synergy#4327] opened 2015-01-19 06:43 UTC

**Comment by erichahn** [comment] 2015-01-20 16:42
I'd like to second this option. Especially between Windows and Linux(ubuntu) machines.

**Comment by Trucido** [comment] 2015-05-19 21:34
please also make this hotkeyable to toggle on/off

**Comment by XinyuHou** [comment] 2015-06-12 18:13
Fixed by 1e89aa37c5df8cdecce065e193ced8c532ee2526

**Comment by nbolton** [comment] 2015-06-18 17:51
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf

**Comment by Trucido** [comment] 2015-06-21 16:21
doesn't seem stable to me with same version running on win 8.1 server and Linux Mint client. love the no-drag feature though so I can snap windows, but it often looses connection and copy/paste seems broken. I'll have to investigate logs when I have time. previous commits from master were working fine though.

**Comment by XinyuHou** [comment] 2015-06-22 17:09
@Trucido 

Does it happen mostly  when you paste on Linux side?

If so, it is related to #4740

**Comment by Trucido** [comment] 2015-06-22 20:30
@XinyuHou not entirely sure, seemed to not transfer clipboard when copying on linux side and trying to paste on windows(server) side. not using SSL.

I've been running it for about a day so far with no issues until today, server service randomly stopped and I had to restart it. windows server log had this after I had to restart it. too bad there's no timestamps, unsure when these occurred. I had debug off on linux side just as a test.

-----synergys.log - 1.7.4 Windows8.1 x64-----
INFO: disconnecting client "Lyra"
INFO: client "Lyra" has disconnected
INFO: stopped server
WARNING: detected application not running, pid=1644
INFO: backing off, wait=2s, failures=1
INFO: starting new process
INFO: activeDesktop:Screen-saver
INFO: starting new process
ERROR: failed to get desktop path, no drop target available, error=2
WARNING: failed to register hotkey Shift+Control+Alt+ScrollLock (id=ef14 mask=0007)
WARNING: failed to register hotkey Shift+Control+Alt+ScrollLock (id=ef14 mask=0007)
WARNING: failed to register hotkey Shift+Control+Alt+ScrollLock (id=ef14 mask=0007)
INFO: started server, waiting for clients
INFO: watchdog status: ok
INFO: accepted client connection
INFO: client "Lyra" has connected
...
INFO: watchdog status: ok
DEBUG: removed log file argument and filename C:/Users/Star/bin/Synergy/log/synergy.log from command 
DEBUG: new command, elevate=0 command=C:/Users/Star/bin/Synergy/synergys.exe -f --no-tray --debug DEBUG --name Mira --ipc --stop-on-desk-switch --profile-dir C:\Users\Star\AppData\Local -c C:/Users/Star/AppData/Local/Temp/qt_temp.Hp1752 --address :24800
------------------------------------------------------------
----synergyc 1.7.4 Linux 4.0-5 (Linux Mint)-------
(wasn't running debug on client during the disconnect)
(clipboard transfer issue, even just copying from terminal or plain text from leafpad)
Jun 22 16:26:19 Lyra Synergy 1.7.4: INFO: leaving screen
Jun 22 16:26:19 Lyra Synergy 1.7.4: DEBUG: open clipboard 0
Jun 22 16:26:19 Lyra Synergy 1.7.4: DEBUG: ICCCM fill clipboard 0
Jun 22 16:26:19 Lyra Synergy 1.7.4: DEBUG:   available targets: STRING (31)
Jun 22 16:26:21 Lyra Synergy 1.7.4: DEBUG: close clipboard 0
Jun 22 16:26:21 Lyra Synergy 1.7.4: DEBUG: open clipboard 1
Jun 22 16:26:21 Lyra Synergy 1.7.4: DEBUG: ICCCM fill clipboard 1
Jun 22 16:26:22 Lyra Synergy 1.7.4: DEBUG:   available targets: STRING (31)
=========Windows server==============
INFO: switch from "Lyra" to "Mira" at 2558,898
INFO: entering screen
DEBUG: open clipboard
DEBUG: empty clipboard
DEBUG: close clipboard
DEBUG: open clipboard
DEBUG: empty clipboard
DEBUG: close clipboard
DEBUG: start receiving clipboard data
NOTE: Clipboard Transmission Started: Start receiving 4 bytes of clipboard data.
DEBUG: received client "Lyra" clipboard 0 seqnum=21, size=4
NOTE: Clipboard Transmission Complete: Clipboard is updated.
DEBUG: ignored screen "Lyra" update of clipboard 0 (unchanged)
DEBUG: start receiving clipboard data
NOTE: Clipboard Transmission Started: Start receiving 4 bytes of clipboard data.
DEBUG: received client "Lyra" clipboard 1 seqnum=21, size=4
NOTE: Clipboard Transmission Complete: Clipboard is updated.
DEBUG: ignored screen "Lyra" update of clipboard 1 (unchanged)
===========================
--------------------------------------------------------------

I noticed there's no option in the config file for the no drag & drop but manually configuring executes it properly without --enable-drag-drop

strangely most of my issues occured with debug level FATAL on both server and client, I'll have to test some more. I think perhaps some clipboard types may be crashing the client or the server? ill continue to investigate and hopefully provide better logs.

**Comment by XinyuHou** [comment] 2015-06-22 21:03
@Trucido 

Thank you for the information.

We added a fix related to service crash and a pull request to disable drag&drop in the nightly. To disable drag and drop you need to go to configure server -> Advanced server settings.

http://synergy-project.org/nightly?filter=415ac8e

if you can see the error message like "virtual bool XWindowsClipboard::open(IClipboard::Time) const: Assertion `!m_open' failed.", then it is related to #4740 

if you can see the error message like "X Error of failed request: BadMatch (invalid parameter attributes).", then it is related to #4814

> strangely most of my issues occured with debug level FATAL on both server and client

Did you mean set log level to FATAL can make the the issue happen more?

> I think perhaps some clipboard types may be crashing the client or the server?

Currently Synergy clipboard only supports text, html and bitmap.

**Comment by Trucido** [comment] 2015-06-22 21:14
@XinyuHou Yeah the log level set to FATAL I was getting the most issues, but I don't have solid evidence of this yet.

I did have the server advanced settings set to disable drag & drop, and I suppose it IS a service thing since it's just a command and not a config option (though perhaps it should be).

I assume to get those types of debug info I'd need to set to DEBUG1 or DEBUG2? 

I'll continue testing newer revisions with drag & drop disabled when I have time. There's still much I haven't ruled out as the cause(s). 

Thanks, love the new feature.

**Comment by XinyuHou** [comment] 2015-06-22 21:29
@Trucido 

Thank you for testing.

We actually removed Error and Warning logging levels in the newer nightly. Firstly because we always want to show them and secondly they tends to cause some other issues. For example, when set log level to Error, client doesn't warn about new fingerprint.

> I did have the server advanced settings set to disable drag & drop, and I suppose it IS a service thing 

Sorry I don't understand what you mean. Disable drag and drop in advanced settings would pass a new command to service without --enable-drag-drop. Then service would use the new command to start synergys/c.

**Comment by Trucido** [comment] 2015-06-23 04:11
hmm this is interesting...
Jun 22 21:46:56 Lyra Synergy 1.7.4: INFO: disconnected from server
Jun 22 21:46:57 Lyra kernel: [708366.299391] synergyc[4812]: segfault at 0 ip           (null) sp 00007ffe614cdda8 error 14 in synergyc[400000+a5000]

I'll try rebooting the box in case some stale libs are in play here.

**Comment by Trucido** [comment] 2015-06-24 23:08
Well I don't know if this is related to the new drag & drop feature but the latest master builds have been really unstable/unreliable for me. synergyc on linux needs to be restarted a lot - it seems to get stoned and won't reconnect to server again. a good example of this is when an elevated prompt appears on windows server, if you wait too long the synergy connection drops.

also, still major copy+paste bugs, copying from windows server to linux client seems to work most of the time, but the other way around it hardly ever works - even plain text, it just doesn't fill the clipboard on windows/server side.

everything was fine on synergy-v1.7.4 b7dfd10

**Comment by XinyuHou** [comment] 2015-06-24 23:36
@Trucido 

Did you rerun wizard to get the latest plugin?

**Comment by Trucido** [comment] 2015-06-24 23:37
@XinyuHou plugin? do you mean the SSL thing? I'm not using encryption

**Comment by Trucido** [comment] 2015-06-24 23:44
well here's my latest segfault log on DEBUG2 http://pastebin.com/kat8ZGeW all I did was try to copy some text from chrome and then copy some text from KiTTY terminal on windows.

**Comment by XinyuHou** [comment] 2015-06-24 23:48
Sorry, my bad.

> an elevated prompt appears on windows server, if you wait too long the synergy connection drops and often won't reconnect.

This is another feature called auto elevated. It probably takes 5~10 seconds to reconnect.

There are 2 issues that have been raised for copying from Linux. #4827 #4814

You can identify them by check the log information, Debug level required.

**Comment by Trucido** [comment] 2015-06-24 23:49
yeah I'd rather not run synergys elevated though and I don't see why it should stone the client and not reconnect. I see #4815 was closed with a commit, I'll try the latest master

**Comment by XinyuHou** [comment] 2015-06-24 23:52
Interesting. That could be another clipboard issue. I need to do more research on that.

As far as I can tell #4815 is not closed.

**Comment by Trucido** [comment] 2015-06-24 23:54
@XinyuHou Yeah I misread. Anyways, clipboard bug could definitely be related - perhaps if the client doesn't get a timely or appropriate response from the server it causes it to segfault?

**Comment by XinyuHou** [comment] 2015-06-25 00:00
@Trucido 

I can't answer you question without looking into code. I will get back to you when I have more information. Thanks for all the work.

**Comment by XinyuHou** [comment] 2015-06-25 18:39
> well here's my latest segfault log on DEBUG2 http://pastebin.com/kat8ZGeW all I did was try to copy some text from chrome and then copy some text from KiTTY terminal on windows. this probably belongs in #4815 though

Copy some text from Chrome on Linux client and then copy some text from KITTY terminal on Windows server?

**Closed** 2015-11-19 00:32 UTC
Labels: enhancement, sprint-must

**Comment by mjsmith1568** [comment] 2016-06-03 12:50
Testing Synergy 1.8.1-beta-b25ed99 build Fri Jun 3rd 2016
Tried the Enable/Disable drag and drop feature between MacOSX10.11(server) and MacOSX10.10(client). This feature works, however, after changing the server configuration setting and pressing OK, the feature is not enabled/disabled until the Apply button is pressed on the main GUI window. Can the changing of server settings and pressing OK also trigger an automatic Apply to lock in the changes? Seems like an unnecessary second step.

**Comment by kdoteu** [comment] 2016-07-01 22:15
Tested on Windows 64bit (Server) und MacOSX 10.11.5(Client)
Disable drag'n'drop feature preventing drag'n'drop beetwen PCs. But as @mjsmith1568 mentioed I had to press apply first

**Comment by alexandercerutti** [comment] 2016-07-01 22:26
I cannot drag and drop either with and without the option enabled. I have just to drag a file from one screen to the other one, haven't I?

**Comment by kdoteu** [comment] 2016-07-01 22:29
@alexandercerutti yes drag'n'drop like you would move an icon on the desktop

**Comment by alexandercerutti** [comment] 2016-07-01 22:30
Yes, I cannot do that. I drag but it not transfer anything.

**Comment by Verequies** [comment] 2016-07-02 02:57
Can confirm that drag and drop doesn't work on Windows 10 Enterprise 64-bit (Can't drag a file through to the other desktop, stops me at the border). However, for me, it never worked. I'm pretty sure it never worked because it can't get/find the desktop path as hinted by this error:
`ERROR: failed to get desktop path, no drop target available, error=2`

**Comment by joshburgess79** [comment] 2016-07-02 04:58
I cannot drag and drop a file with the box checked or not. Both my client and server are Ubuntu 16.04 64-bit

**Comment by yidhoe** [comment] 2016-07-02 13:15
Yes Drag and Drop works until the box is unticked and the server restarted. :)

Clients Win 10 32+64.
Server Win 10 64.

**Comment by cletsimon** [comment] 2016-07-03 11:16
I cannot drat and drop a file even drag and drop feature is enabled.
Server: OSX 10.10.5
Client: Ubuntu 14.14

**Comment by Bazzek** [comment] 2016-07-05 06:51
Cannot drag and drop between Xubuntu and Kubuntu (both 16.04) when the option is enabled (or disabled).

Wonder if it is a ubuntu family issue (based on my and above mentioned experiences.

**Comment by wbryanharris** [comment] 2016-07-07 14:45
Cannont drag and drop between OSX El Capitan and Win 7 at all.  Changing the check box has no effect.  When dragging the file, it "drops off" the cursor as the cursor moves from Mac to Win.  Log shows error message that says "WARNING: Cursor may not be visable".  Cursor is visable, but no file.  Dragging Win to Mac results in:
ERROR: failed to drop target
ERROR: drop file failed: drop target is empty

**Comment by carboncopy-my** [comment] 2016-07-08 02:57
Cannot drag and drop between Fedora 24 (4.5.7-300.fc24.x86_64) and Centos 7 (3.10.0-327.22.2.el7.x86_64) Enabled (or disabled) How to submit log?

**Comment by BoStaahle** [comment] 2016-07-08 07:23
With Win10 x64 as server and a Mac OSX 10.11 as client it seems to work as intended.
(1.8.1-beta-f7377d6)

**Comment by Bazzek** [comment] 2016-07-08 11:56
I have started a new topic (#5353) to get this ball rolling. If you cannot drag drop irregardless of the flag, please post it in THAT issue, not here.

**Comment by clomedico** [comment] 2017-03-28 18:48
Lost connection between computers (Windows 10 and Mac OS X 10.12). Worked fine this morning then nothing. Uninstalled, rebooted, reinstalled and now not working
