### ISSUE TITLE
Recognize Existing Multi-Monitor Setup (to allow accurate client monitor positioning)

### ISSUE THREAD

**Issue by ColinCreamer** [synergy/synergy#4795] opened 2015-06-12 20:52 UTC
When adding client machines to a server sharing its keyboard and mouse, there is a window where you position the client machines monitor, relative to that of the server machine.

![image](https://cloud.githubusercontent.com/assets/2904388/8139246/04d03f1a-1120-11e5-9535-3a22f6feb835.png)

No mater what, it assumes that you are using a single monitor setup. It would be great if this interface was improved to detect the servers existing monitor set up, and then let you position the client machine relative to the server's actual monitor setup.

![image](https://cloud.githubusercontent.com/assets/2904388/8139449/e4e44dfc-1121-11e5-87e8-9b07237d4707.png)

Essentially you would need to detect the resolution and position of each monitor on the system, and then create a non-movable monitor cluster representation, that the user can the position their client machine around.

If you wanted to take it one step further, you could also detect the the resolutions for the monitors on the client machine, and use that to generate a similar monitor cluster image for them as well, to use instead of the single monitor icon.(of course this one would be movable)

**Comment by speaker** [comment] 2015-06-16 23:41
Agree! In fact, my setup is even more complicated because I have one monitor in portrait mode, and the other in landscape. That scenario causes only the top and bottom of the portrait monitors to act as the edge. 

Effectively this is a duplicate of #3744

**Closed by speaker** 2015-06-16 23:41 UTC
Labels: enhancement, feature-idea, v1.7

**Comment by thedyerman** [comment] 2015-11-17 13:56
I second this feature, I have 7 monitors, two of which are  different ubuntu machines and ones a mac. I would love it if there was some type of automatic screen scaling @ColinCreamer said above.
