### ISSUE TITLE
Synergy Icon Update

### ISSUE THREAD

**Issue by psthompson** [synergy/synergy#4129] opened 2014-10-16 22:27 UTC
Not really an issue but a feature request.

The new flat look of the Synergy Icon on the website is great, but the icon shown in the app switcher on Mac is in need of an update

![synergy icon](https://cloud.githubusercontent.com/assets/2582474/4671653/828e5904-5583-11e4-96a3-f855353ce23a.png)

**Comment by cabe83** [comment] 2015-01-01 21:24
+1 on this, great app, but the icon is an eyesore on the retina Mac, kinda sucks out. Looking forward to this little cosmetic update.

**Comment by the-wes** [comment] 2015-02-23 22:11
Duplicate of https://github.com/synergy/synergy/issues/3791

**Closed by the-wes** 2015-02-23 22:11 UTC
Labels: enhancement

**Comment by nbolton** [comment] 2015-03-02 08:09
@the-wes: Please remove milestone if duplicate/invalid, thanks.
