### ISSUE TITLE
Drag and drop with SSL causes crash

### ISSUE THREAD

**Issue by XinyuHou** [synergy/synergy#4584] opened 2015-04-28 15:11 UTC
Mac 10.10

1. Setup Mac as either server or client.
2. Connect with SSL on.
3. Drag a file from Mac and drop it to the other side.

Expect: file is created on the other side.
Actual: Mac side disconnected with error message as below.

secure socket error: SSL_ERROR_SSL
error:140D00CF:SSL routines:SSL_write:protocol is shutdown

**Comment by nbolton** [comment] 2015-05-01 17:00
Maybe related: #4601

**Comment by nbolton** [comment] 2015-05-13 09:22
@XinyuHou @speaker I'm pretty certain this is a duplicate of #4601.

**Comment by nbolton** [comment] 2015-05-13 09:23
Hmm, though I guess we should leave it open since users might find this useful on the ChangeLog.

**Comment by nbolton** [comment] 2015-05-21 08:20
Duplicates #4601

**Comment by XinyuHou** [comment] 2015-05-28 23:14
Could someone test this nightly?

http://synergy-project.org/nightly?filter=dba4670

Right now there is no indication to tell if the transfer is finished expect from watching the logging. A solution would be added in next release.

**Comment by shoelzer** [comment] 2015-05-29 14:32
I tried nightly dba4670 on two Win 7 x64 computers. Updating clipboards seems to work but I see these errors in the client log:

    ERROR: corrupted clipboard data, expected size=16562 actual size=0
    ...
    ERROR: corrupted clipboard data, expected size=37651 actual size=20480

Drag and drop works only for small files (178 bytes worked). The first time I tried a large file (60 MB) I got a disconnect and the computer became very unresponsive until I killed Synergy. Now when I try nothing at all seems to happen. The file is not transferred, there's no log message, and the computer does not bog down.

**Comment by XinyuHou** [comment] 2015-05-29 16:29
@shoelzer 
Which log level are you using? You can change it in settings.

Are your two machines setup vertically or horizontally?

**Comment by shoelzer** [comment] 2015-05-29 18:24
@XinyuHou 

"Info" log level. I changed to "Debug" and got this on the server:

~~~
INFO: leaving screen
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 0 (unchanged)
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 1 (unchanged)
DEBUG: dropped bogus delta motion: -843,+252
DEBUG: sending file to client, filename=C:\Users\shoelzer\Desktop\file.pptx
INFO: switch from "Li-HPZ420" to "LI4LJB5RH12" at 16,720
INFO: entering screen
INFO: switch from "LI4LJB5RH12" to "Li-HPZ420" at 1919,725
INFO: leaving screen
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 0 (unchanged)
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 1 (unchanged)
DEBUG: ssl connection closed
NOTE: client "Li-HPZ420" has disconnected
~~~

On the client I see `drag info received` and then a short while later `disconnected from server`.

I have a horizontal setup with the client to the left of the server.

**Comment by XinyuHou** [comment] 2015-06-02 21:06
@shoelzer 
Thank you for the logging which is really helpful.

I think there are at least two causes for the issue.

1. Drag a big file that is over SSL socket limit.
2. For some reason, when you move cursor to client, occasionally it bounces back and forth, then finally lands on client's screen. This itself is not a problem. But when it happens while dragging, an unhandled exception will close the process when move cursor back.

Could you please test this nightly, which is intended to fix the first scenario?

http://synergy-project.org/nightly?filter=8d0fdee

**Comment by XinyuHou** [comment] 2015-06-02 21:49
@shoelzer 
Just found out, using relative mouse moves can eliminate the second scenario on my machine.

To use relative mouse moves, click configure server->advanced server settings->use relative mouse moves.

**Comment by shoelzer** [comment] 2015-06-03 13:42
@XinyuHou

Thanks for your work on this issue! It will be so nice to get it working reliably. I turned on relative mouse moves and don't think that the bounce has happened since then. I don't know what it's doing but it seems to work.

I tried nightly 8d0fdee. One thing about this build that I've never seen before is notifications from the taskbar. When I move the mouse back and forth between machines I got quite a lot of notifications saying "Clipboard Transmission Ignored. Clipboard data hasn't changed." They also appear in the log.

I tried dragging files with 8d0fdee but it still disconnects with large files. I tried with my original 60 MB file and also a 784 KB file. Files under 200 bytes work reliably.

Here's the server log from one failed test:

~~~
DEBUG: locked by "Left Button"
INFO: switch from "LI4LJB5RH12" to "Li-HPZ420" at 1919,799
INFO: leaving screen
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 0 (unchanged)
NOTE: Clipboard Transmission Ignored: Clipboard data hasn't changed.
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 1 (unchanged)
NOTE: Clipboard Transmission Ignored: Clipboard data hasn't changed.
DEBUG: dropped bogus delta motion: -842,+252
DEBUG: sending file to client, filename=C:\file.exe
DEBUG: ssl connection closed
INFO: client "Li-HPZ420" has disconnected
INFO: jump from "Li-HPZ420" to "LI4LJB5RH12" at 840,525
INFO: entering screen
DEBUG: active sides: 2
INFO: accepted client connection
INFO: accepted secure socket
DEBUG: received client "Li-HPZ420" info shape=0,0 1920x1080 at 0,0
DEBUG: active sides: 2
INFO: client "Li-HPZ420" has connected
~~~

And here's the matching client log:

~~~
INFO: entering screen
DEBUG: drag info received, total drag file number: 1
DEBUG: dragging file 1 name: file.exe
NOTE: File Transmission Started: Start receiving file.exe.
INFO: leaving screen
INFO: disconnected from server
DEBUG: retry in 1 seconds
INFO: connecting to 'LI4LJB5RH12': 10.27.108.22:24800
NOTE: server fingerprint: 5B:2D:33:C3:0D:59:8C:1A:C9:95:8A:5B:D5:9D:21:FB:D9:B2:EF:F6
INFO: connected to secure socket
INFO: server ssl certificate info: /CN=Synergy
DEBUG: desk Default window is 0x00270320
DEBUG: switched to desk "Default"
DEBUG: desktop is now accessible
DEBUG: open clipboard
DEBUG: empty clipboard
DEBUG: close clipboard
DEBUG: open clipboard
DEBUG: empty clipboard
DEBUG: close clipboard
INFO: connected to server
DEBUG: recv grab clipboard 0
DEBUG: open clipboard
DEBUG: empty clipboard
DEBUG: close clipboard
DEBUG: recv grab clipboard 1
DEBUG: open clipboard
DEBUG: empty clipboard
DEBUG: close clipboard
~~~

**Comment by shoelzer** [comment] 2015-06-03 13:48
@XinyuHou

One more thing I just noticed about 8d0fdee: It seems to double log clipboard transfers. Example below.

Server:

~~~
INFO: switch from "LI4LJB5RH12" to "Li-HPZ420" at 1919,564
INFO: leaving screen
NOTE: Clipboard Transmission Ignored: Clipboard data hasn't changed.
NOTE: Clipboard Transmission Ignored: Clipboard data hasn't changed.
INFO: screen "Li-HPZ420" grabbed clipboard 0 from "LI4LJB5RH12"
INFO: screen "Li-HPZ420" grabbed clipboard 1 from "LI4LJB5RH12"
~~~

Client:

~~~
INFO: entering screen
NOTE: Clipboard Transmission Started: Start receiving 594 bytes of clipboard data.
NOTE: Clipboard Transmission Complete: Clipboard is updated.
NOTE: Clipboard Transmission Started: Start receiving 594 bytes of clipboard data.
NOTE: Clipboard Transmission Complete: Clipboard is updated.

**Comment by shoelzer** [comment] 2015-06-03 14:02
@XinyuHou

And one more: synergyd.exe uses 100% of one core on the client machine when I move the mouse from server to client. If I open the Synergy GUI then CPU usage goes to zero. Usage stays at zero when I close the GUI and go back to server. Usage returns to 100% when I go back to client.

**Comment by XinyuHou** [comment] 2015-06-03 16:53
@shoelzer 
When you drag a big file, did you move your cursor back before the notification says it is done?

For double log clipboard transfers, it is by design. Synergy actually copy 2 clipboards. I need to spend more time in digging out why. Maybe some legacy reasons.

High CPU usage from synergyd, we have a fix ready for test, but I haven't merge the fix into my branch. I will remember to do it before I sent next nightly build.

Thank you so much for the feedback!

**Comment by shoelzer** [comment] 2015-06-03 17:52
@XinyuHou 
I did not move the cursor back during file transfer. I waited on the client and the disconnect happened after just about 2 seconds which forced me back to the server.

**Comment by XinyuHou** [comment] 2015-06-06 01:05
@shoelzer 
Can anyone test this nightly?

http://synergy-project.org/nightly?filter=5c71efe

Note: After installation you need to replace the plugins. Here are the links and the directories of plugins.

Win64
https://drive.google.com/open?id=0B9JIQhrszoq2UUJSYU5WeWlOem8&authuser=0
X:\Users\xxx\AppData\Local\Synergy\Plugins

MacOSX10.10
https://drive.google.com/open?id=0B9JIQhrszoq2UnZRSDJaOUZlUFE&authuser=0
/Users/xxx/Library/Synergy/Plugins

**Comment by shoelzer** [comment] 2015-06-08 13:28
@XinyuHou
I tried 5c71efe and it fixed some things but not everything. One nice thing is that "bounce" seems to be fixed. I was able to turn off "use relative motion" and haven't had a problem. Transferring small and medium files (tested up to 784 KB) works reliably. High CPU usage is fixed.

[Aside: File transfers are a lot slower that I expected, even for these small files. It can take a couple seconds to complete. My machines are both connected to a local wired network with gigabit Ethernet and transferring files using Windows Shares happens instantly as far as I can tell.]

[Aside 2: I noticed that moving the mouse to a different machine while a file transfer is in progress cancels the file transfer. Is that intentional? In some ways it makes sense, but if I have a large file and file transfer is slow (and it is), then I would prefer that the transfer continue until completion.]

Transferring a 60 MB file still fails and disconnects. It takes over a minute before that happens, and the errors are different so hopefully it won't be hard to find and fix these problems. Here are logs from one test. First I copied "file.exe" (784 KB) successfully, then I tried to copy "file2.pptx" (60 MB).

Sever log:

~~~
NOTE: connecting to service...
NOTE: connection established
DEBUG: finished ipc handle data
DEBUG: ipc hello, type=gui
INFO: watchdog status: ok
DEBUG: locked by "Left Button"
INFO: switch from "LI4LJB5RH12" to "Li-HPZ420" at 1919,935
INFO: leaving screen
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 0 (unchanged)
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 1 (unchanged)
DEBUG: sending file to client, filename=C:\Users\shoelzer\Desktop\file.exe
INFO: switch from "Li-HPZ420" to "LI4LJB5RH12" at 4,894
INFO: entering screen
DEBUG: clipboard changed: lost ownership
INFO: screen "LI4LJB5RH12" grabbed clipboard 0 from "LI4LJB5RH12"
DEBUG: send grab clipboard 0 to "Li-HPZ420"
INFO: screen "LI4LJB5RH12" grabbed clipboard 1 from "LI4LJB5RH12"
DEBUG: send grab clipboard 1 to "Li-HPZ420"
DEBUG: locked by "Left Button"
INFO: switch from "LI4LJB5RH12" to "Li-HPZ420" at 1919,660
INFO: leaving screen
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 0 (unchanged)
DEBUG: open clipboard
DEBUG: close clipboard
DEBUG: ignored screen "LI4LJB5RH12" update of clipboard 1 (unchanged)
DEBUG: sending clipboard 0 to "Li-HPZ420"
DEBUG: dropped bogus delta motion: -844,+110
DEBUG: sent clipboard size=4
DEBUG: sending clipboard 1 to "Li-HPZ420"
DEBUG: sent clipboard size=4
DEBUG: sending file to client, filename=C:\Users\shoelzer\Desktop\file2.pptx
ERROR: ssl error occurred (generic failure)
ERROR: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
INFO: client "Li-HPZ420" has disconnected
INFO: jump from "Li-HPZ420" to "LI4LJB5RH12" at 840,525
INFO: entering screen
DEBUG: active sides: 2
INFO: accepted client connection
INFO: accepted secure socket
DEBUG: ssl connection closed
INFO: client "Li-HPZ420" has disconnected
INFO: new client disconnected
INFO: accepted client connection
INFO: accepted secure socket
DEBUG: received client "Li-HPZ420" info shape=0,0 1920x1080 at 0,0
DEBUG: active sides: 2
INFO: client "Li-HPZ420" has connected
~~~

Client log:

~~~
NOTE: connecting to service...
NOTE: connection established
INFO: watchdog status: ok
INFO: entering screen
NOTE: File Transmission Started: Start receiving file.exe.
NOTE: File Transmission Complete: file.exe is saved to C:\Users\shoelzer\Desktop.
INFO: leaving screen
NOTE: File Transmission Interrupted: The previous file transmission is interrupted.
INFO: entering screen
NOTE: Clipboard Transmission Started: Start receiving 4 bytes of clipboard data.
NOTE: Clipboard Transmission Complete: Clipboard is updated.
NOTE: Clipboard Transmission Started: Start receiving 4 bytes of clipboard data.
NOTE: Clipboard Transmission Complete: Clipboard is updated.
NOTE: File Transmission Started: Start receiving file2.pptx.
ERROR: ssl error occurred (system call failure)
ERROR: eof violates ssl protocol
INFO: leaving screen
INFO: disconnected from server
INFO: stopped client
WARNING: detected application not running, pid=3280
INFO: backing off, wait=2s, failures=1
INFO: starting new process
INFO: activeDesktop:Default
INFO: starting new process
INFO: drag and drop enabled
INFO: started client
INFO: connecting to 'LI4LJB5RH12': 10.27.108.23:24800
INFO: watchdog status: ok
INFO: server fingerprint: 5B:2D:33:C3:0D:59:8C:1A:C9:95:8A:5B:D5:9D:21:FB:D9:B2:EF:F6
INFO: connected to secure socket
INFO: server ssl certificate info: /CN=Synergy
INFO: server is dead
WARNING: failed to connect to server: server is not responding
INFO: connecting to 'LI4LJB5RH12': 10.27.108.23:24800
INFO: server fingerprint: 5B:2D:33:C3:0D:59:8C:1A:C9:95:8A:5B:D5:9D:21:FB:D9:B2:EF:F6
INFO: connected to secure socket
INFO: server ssl certificate info: /CN=Synergy
INFO: connected to server
~~~

**Comment by shoelzer** [comment] 2015-06-08 15:26
@XinyuHou
Another thing about 5c71efe: The server shows "Clipboard Transmission Complete" in the taskbar when moving from client to server if the clipboard has changed. This doesn't hurt anything, but doesn't seem necessary to report all the time either.

**Comment by XinyuHou** [comment] 2015-06-08 17:06
@shoelzer 

Again thank you so much for the feedback!

> "bounce" seems to be fixed
I'm not sure the bounce issue is fixed. Maybe it is just intermittent. One thing I notice is if you slowly move your cursor to another screen, there is no bounce.

> File transfers are a lot slower that I expected
I think this is an inherent disadvantage of using SSL to transfer big data. SSL record limits its size to 16kb, which can only contain 2k or 4k actual data. Right now it is using 2k buffer for each socket. I will try 4k. The last time when I tried 4k, it crashed a lot due to over sized. Maybe in the future we need another protocol to transfer big data.

>  moving the mouse to a different machine while a file transfer is in progress cancels the file transfer
It is the simplest way to implement so far. I like your idea. However it would be a big story in this release. After this release I will create a ticket for that.

> Transferring a 60 MB file still fails and disconnects.
Just curious, did you replace ns.dll with the link I posted? We don't have any version system for plugins right now, so, even for developers, we could easily mess up and use the wrong or old plugins. My colleague, Adam, is working on this issue.

I tested with a 40mb file, it seems to work ok, but I will keep testing.

> The server shows "Clipboard Transmission Complete" in the taskbar when moving from client to server if the clipboard has changed
Did you mean to say if the clipboard has not changed?

Thanks again!

**Comment by XinyuHou** [comment] 2015-06-08 17:58
Tested with a 100 mb file on 2 Windows 7 machines and a Windows 7 server and a Mac OSX 10.10 client.

They all seem to work alright. The average speed seems to be 500kb/s.

**Comment by shoelzer** [comment] 2015-06-08 18:09
@XinyuHou 
Thanks for all the info. I'll keep watching for the bounce issue. I did replace ns.dll on both machines for my earlier tests.

I just tested again but before that I restarted the Synergy service on my server and client. After that, the 60 MB file worked! It took more than a minute but I certainly prefer a slow transfer over failing and disconnecting.

The "Clipboard Transmission Complete" message shows up when I'm on the client, copy some text, the move to the server. That happens every time the clipboard changes on the client and then I move to the server.

**Comment by XinyuHou** [comment] 2015-06-08 19:45
@shoelzer 
Glad it is working!

The average speed seems to be 500kb/s. I will try to improve the speed.

The clipboard complete massage showing up is intended for the cases where the clipboard data is big. Additionally it is a good indication that the clipboard is updated and ready to be used. Because sometimes copy paste doesn't work for some reason.

**Comment by XinyuHou** [comment] 2015-06-08 23:09
Can anyone test this nightly?

http://synergy-project.org/nightly?filter=8e15b77

Note: you need to rerun wizard to get the latest plugins.

Feedback welcome!

**Comment by shoelzer** [comment] 2015-06-09 13:58
@XinyuHou 
8e15b77 works for me. Seems to behave the same as the last nightly.

**Closed** 2015-06-09 23:12 UTC
Labels: bug, priority-urgent, v1.7

**Comment by nbolton** [comment] 2015-06-18 17:51
Please test this pre-release to confirm this is ready for release.
http://synergy-project.org/nightly?filter=v1.7.4-stable-ebb7edf
