### ISSUE TITLE
Pressing winkey on Win7 triggering Ubuntu12 dash home

### ISSUE THREAD

**Issue by Matthijs-Wessels** [synergy/synergy#4383] opened 2015-02-26 08:51 UTC
When I press the Windows Key when my mouse is on my Windows 7 laptop, it works find and I get the start menu and can search in it etc. However, when I move the mouse back to my Ubuntu 12.04 desktop the Dash Home menu expands.

I am using a Ubuntu 12.04 LTS for my desktop, this is the server and has two screens.
I am using Windows 7 for my laptop and it's standing on the right of my desktop.

**Comment by luser** [comment] 2015-02-26 12:54
Dupe of https://github.com/synergy/synergy/issues/4379

**Closed** 2015-02-26 15:25 UTC
